// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/userdefinednetwork/v1"
	userdefinednetworkv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/userdefinednetwork/v1/apis/applyconfiguration/userdefinednetwork/v1"
	typeduserdefinednetworkv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/userdefinednetwork/v1/apis/clientset/versioned/typed/userdefinednetwork/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeUserDefinedNetworks implements UserDefinedNetworkInterface
type fakeUserDefinedNetworks struct {
	*gentype.FakeClientWithListAndApply[*v1.UserDefinedNetwork, *v1.UserDefinedNetworkList, *userdefinednetworkv1.UserDefinedNetworkApplyConfiguration]
	Fake *FakeK8sV1
}

func newFakeUserDefinedNetworks(fake *FakeK8sV1, namespace string) typeduserdefinednetworkv1.UserDefinedNetworkInterface {
	return &fakeUserDefinedNetworks{
		gentype.NewFakeClientWithListAndApply[*v1.UserDefinedNetwork, *v1.UserDefinedNetworkList, *userdefinednetworkv1.UserDefinedNetworkApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("userdefinednetworks"),
			v1.SchemeGroupVersion.WithKind("UserDefinedNetwork"),
			func() *v1.UserDefinedNetwork { return &v1.UserDefinedNetwork{} },
			func() *v1.UserDefinedNetworkList { return &v1.UserDefinedNetworkList{} },
			func(dst, src *v1.UserDefinedNetworkList) { dst.ListMeta = src.ListMeta },
			func(list *v1.UserDefinedNetworkList) []*v1.UserDefinedNetwork {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.UserDefinedNetworkList, items []*v1.UserDefinedNetwork) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
