/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	vtepv1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/vtep/v1"
	applyconfigurationvtepv1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/vtep/v1/apis/applyconfiguration/vtep/v1"
	scheme "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/vtep/v1/apis/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VTEPsGetter has a method to return a VTEPInterface.
// A group's client should implement this interface.
type VTEPsGetter interface {
	VTEPs() VTEPInterface
}

// VTEPInterface has methods to work with VTEP resources.
type VTEPInterface interface {
	Create(ctx context.Context, vTEP *vtepv1.VTEP, opts metav1.CreateOptions) (*vtepv1.VTEP, error)
	Update(ctx context.Context, vTEP *vtepv1.VTEP, opts metav1.UpdateOptions) (*vtepv1.VTEP, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, vTEP *vtepv1.VTEP, opts metav1.UpdateOptions) (*vtepv1.VTEP, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*vtepv1.VTEP, error)
	List(ctx context.Context, opts metav1.ListOptions) (*vtepv1.VTEPList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *vtepv1.VTEP, err error)
	Apply(ctx context.Context, vTEP *applyconfigurationvtepv1.VTEPApplyConfiguration, opts metav1.ApplyOptions) (result *vtepv1.VTEP, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, vTEP *applyconfigurationvtepv1.VTEPApplyConfiguration, opts metav1.ApplyOptions) (result *vtepv1.VTEP, err error)
	VTEPExpansion
}

// vTEPs implements VTEPInterface
type vTEPs struct {
	*gentype.ClientWithListAndApply[*vtepv1.VTEP, *vtepv1.VTEPList, *applyconfigurationvtepv1.VTEPApplyConfiguration]
}

// newVTEPs returns a VTEPs
func newVTEPs(c *K8sV1Client) *vTEPs {
	return &vTEPs{
		gentype.NewClientWithListAndApply[*vtepv1.VTEP, *vtepv1.VTEPList, *applyconfigurationvtepv1.VTEPApplyConfiguration](
			"vteps",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *vtepv1.VTEP { return &vtepv1.VTEP{} },
			func() *vtepv1.VTEPList { return &vtepv1.VTEPList{} },
		),
	}
}
