// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	userdefinednetworkv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/userdefinednetwork/v1"
	applyconfigurationuserdefinednetworkv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/userdefinednetwork/v1/apis/applyconfiguration/userdefinednetwork/v1"
	scheme "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/userdefinednetwork/v1/apis/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterUserDefinedNetworksGetter has a method to return a ClusterUserDefinedNetworkInterface.
// A group's client should implement this interface.
type ClusterUserDefinedNetworksGetter interface {
	ClusterUserDefinedNetworks() ClusterUserDefinedNetworkInterface
}

// ClusterUserDefinedNetworkInterface has methods to work with ClusterUserDefinedNetwork resources.
type ClusterUserDefinedNetworkInterface interface {
	Create(ctx context.Context, clusterUserDefinedNetwork *userdefinednetworkv1.ClusterUserDefinedNetwork, opts metav1.CreateOptions) (*userdefinednetworkv1.ClusterUserDefinedNetwork, error)
	Update(ctx context.Context, clusterUserDefinedNetwork *userdefinednetworkv1.ClusterUserDefinedNetwork, opts metav1.UpdateOptions) (*userdefinednetworkv1.ClusterUserDefinedNetwork, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterUserDefinedNetwork *userdefinednetworkv1.ClusterUserDefinedNetwork, opts metav1.UpdateOptions) (*userdefinednetworkv1.ClusterUserDefinedNetwork, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*userdefinednetworkv1.ClusterUserDefinedNetwork, error)
	List(ctx context.Context, opts metav1.ListOptions) (*userdefinednetworkv1.ClusterUserDefinedNetworkList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *userdefinednetworkv1.ClusterUserDefinedNetwork, err error)
	Apply(ctx context.Context, clusterUserDefinedNetwork *applyconfigurationuserdefinednetworkv1.ClusterUserDefinedNetworkApplyConfiguration, opts metav1.ApplyOptions) (result *userdefinednetworkv1.ClusterUserDefinedNetwork, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, clusterUserDefinedNetwork *applyconfigurationuserdefinednetworkv1.ClusterUserDefinedNetworkApplyConfiguration, opts metav1.ApplyOptions) (result *userdefinednetworkv1.ClusterUserDefinedNetwork, err error)
	ClusterUserDefinedNetworkExpansion
}

// clusterUserDefinedNetworks implements ClusterUserDefinedNetworkInterface
type clusterUserDefinedNetworks struct {
	*gentype.ClientWithListAndApply[*userdefinednetworkv1.ClusterUserDefinedNetwork, *userdefinednetworkv1.ClusterUserDefinedNetworkList, *applyconfigurationuserdefinednetworkv1.ClusterUserDefinedNetworkApplyConfiguration]
}

// newClusterUserDefinedNetworks returns a ClusterUserDefinedNetworks
func newClusterUserDefinedNetworks(c *K8sV1Client) *clusterUserDefinedNetworks {
	return &clusterUserDefinedNetworks{
		gentype.NewClientWithListAndApply[*userdefinednetworkv1.ClusterUserDefinedNetwork, *userdefinednetworkv1.ClusterUserDefinedNetworkList, *applyconfigurationuserdefinednetworkv1.ClusterUserDefinedNetworkApplyConfiguration](
			"clusteruserdefinednetworks",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *userdefinednetworkv1.ClusterUserDefinedNetwork {
				return &userdefinednetworkv1.ClusterUserDefinedNetwork{}
			},
			func() *userdefinednetworkv1.ClusterUserDefinedNetworkList {
				return &userdefinednetworkv1.ClusterUserDefinedNetworkList{}
			},
		),
	}
}
