// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	userdefinednetworkv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/userdefinednetwork/v1"
	applyconfigurationuserdefinednetworkv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/userdefinednetwork/v1/apis/applyconfiguration/userdefinednetwork/v1"
	scheme "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/userdefinednetwork/v1/apis/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// UserDefinedNetworksGetter has a method to return a UserDefinedNetworkInterface.
// A group's client should implement this interface.
type UserDefinedNetworksGetter interface {
	UserDefinedNetworks(namespace string) UserDefinedNetworkInterface
}

// UserDefinedNetworkInterface has methods to work with UserDefinedNetwork resources.
type UserDefinedNetworkInterface interface {
	Create(ctx context.Context, userDefinedNetwork *userdefinednetworkv1.UserDefinedNetwork, opts metav1.CreateOptions) (*userdefinednetworkv1.UserDefinedNetwork, error)
	Update(ctx context.Context, userDefinedNetwork *userdefinednetworkv1.UserDefinedNetwork, opts metav1.UpdateOptions) (*userdefinednetworkv1.UserDefinedNetwork, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, userDefinedNetwork *userdefinednetworkv1.UserDefinedNetwork, opts metav1.UpdateOptions) (*userdefinednetworkv1.UserDefinedNetwork, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*userdefinednetworkv1.UserDefinedNetwork, error)
	List(ctx context.Context, opts metav1.ListOptions) (*userdefinednetworkv1.UserDefinedNetworkList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *userdefinednetworkv1.UserDefinedNetwork, err error)
	Apply(ctx context.Context, userDefinedNetwork *applyconfigurationuserdefinednetworkv1.UserDefinedNetworkApplyConfiguration, opts metav1.ApplyOptions) (result *userdefinednetworkv1.UserDefinedNetwork, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, userDefinedNetwork *applyconfigurationuserdefinednetworkv1.UserDefinedNetworkApplyConfiguration, opts metav1.ApplyOptions) (result *userdefinednetworkv1.UserDefinedNetwork, err error)
	UserDefinedNetworkExpansion
}

// userDefinedNetworks implements UserDefinedNetworkInterface
type userDefinedNetworks struct {
	*gentype.ClientWithListAndApply[*userdefinednetworkv1.UserDefinedNetwork, *userdefinednetworkv1.UserDefinedNetworkList, *applyconfigurationuserdefinednetworkv1.UserDefinedNetworkApplyConfiguration]
}

// newUserDefinedNetworks returns a UserDefinedNetworks
func newUserDefinedNetworks(c *K8sV1Client, namespace string) *userDefinedNetworks {
	return &userDefinedNetworks{
		gentype.NewClientWithListAndApply[*userdefinednetworkv1.UserDefinedNetwork, *userdefinednetworkv1.UserDefinedNetworkList, *applyconfigurationuserdefinednetworkv1.UserDefinedNetworkApplyConfiguration](
			"userdefinednetworks",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *userdefinednetworkv1.UserDefinedNetwork { return &userdefinednetworkv1.UserDefinedNetwork{} },
			func() *userdefinednetworkv1.UserDefinedNetworkList {
				return &userdefinednetworkv1.UserDefinedNetworkList{}
			},
		),
	}
}
