// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HostFunctionApplyConfiguration represents a declarative configuration of the HostFunction type for use
// with apply.
//
// HostFunction identifies a PCI function: a physical function by its index,
// or a virtual function by the PF index and its own index on that PF.
type HostFunctionApplyConfiguration struct {
	// PFID is the index of the physical function backing the host interface.
	PFID *int32 `json:"pfID,omitempty"`
	// VFID is the index of the virtual function on the physical function.
	// Absent when the host interface is the physical function itself.
	VFID *int32 `json:"vfID,omitempty"`
}

// HostFunctionApplyConfiguration constructs a declarative configuration of the HostFunction type for use with
// apply.
func HostFunction() *HostFunctionApplyConfiguration {
	return &HostFunctionApplyConfiguration{}
}

// WithPFID sets the PFID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PFID field is set to the value of the last call.
func (b *HostFunctionApplyConfiguration) WithPFID(value int32) *HostFunctionApplyConfiguration {
	b.PFID = &value
	return b
}

// WithVFID sets the VFID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VFID field is set to the value of the last call.
func (b *HostFunctionApplyConfiguration) WithVFID(value int32) *HostFunctionApplyConfiguration {
	b.VFID = &value
	return b
}
