// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// OVSBridgeStatusApplyConfiguration represents a declarative configuration of the OVSBridgeStatus type for use
// with apply.
type OVSBridgeStatusApplyConfiguration struct {
	// Name is the resolved OVS bridge used for OVN bridge mappings and flows.
	Name *string `json:"name,omitempty"`
}

// OVSBridgeStatusApplyConfiguration constructs a declarative configuration of the OVSBridgeStatus type for use with
// apply.
func OVSBridgeStatus() *OVSBridgeStatusApplyConfiguration {
	return &OVSBridgeStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *OVSBridgeStatusApplyConfiguration) WithName(value string) *OVSBridgeStatusApplyConfiguration {
	b.Name = &value
	return b
}
