// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	uplinkv1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/uplink/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// UplinkNodeConfigApplyConfiguration represents a declarative configuration of the UplinkNodeConfig type for use
// with apply.
type UplinkNodeConfigApplyConfiguration struct {
	// Type is the uplink node config type. Supported value: OVSBridge.
	Type *uplinkv1alpha1.UplinkType `json:"type,omitempty"`
	// NodeSelector selects nodes where this uplink config applies. An empty
	// selector matches all nodes.
	NodeSelector *v1.LabelSelectorApplyConfiguration `json:"nodeSelector,omitempty"`
	// HostInterfaceName is the host-visible Linux interface that carries the
	// gateway L3 identity for this uplink. In non-accelerated deployments,
	// this is typically the OVS bridge Linux interface, whose name usually
	// matches the OVS bridge name. In SmartNIC accelerated deployments, this is
	// the VF/SF netdevice and OVN-Kubernetes resolves the OVS bridge through
	// its representor. In DPU deployments, this is the DPU-host PF interface
	// whose DPU-side PF representor is attached to the OVS bridge.
	HostInterfaceName *uplinkv1alpha1.InterfaceName `json:"hostInterfaceName,omitempty"`
}

// UplinkNodeConfigApplyConfiguration constructs a declarative configuration of the UplinkNodeConfig type for use with
// apply.
func UplinkNodeConfig() *UplinkNodeConfigApplyConfiguration {
	return &UplinkNodeConfigApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *UplinkNodeConfigApplyConfiguration) WithType(value uplinkv1alpha1.UplinkType) *UplinkNodeConfigApplyConfiguration {
	b.Type = &value
	return b
}

// WithNodeSelector sets the NodeSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeSelector field is set to the value of the last call.
func (b *UplinkNodeConfigApplyConfiguration) WithNodeSelector(value *v1.LabelSelectorApplyConfiguration) *UplinkNodeConfigApplyConfiguration {
	b.NodeSelector = value
	return b
}

// WithHostInterfaceName sets the HostInterfaceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostInterfaceName field is set to the value of the last call.
func (b *UplinkNodeConfigApplyConfiguration) WithHostInterfaceName(value uplinkv1alpha1.InterfaceName) *UplinkNodeConfigApplyConfiguration {
	b.HostInterfaceName = &value
	return b
}
