// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// UplinkStateSpecApplyConfiguration represents a declarative configuration of the UplinkStateSpec type for use
// with apply.
type UplinkStateSpecApplyConfiguration struct {
	// UplinkName is the Uplink this state belongs to.
	UplinkName *string `json:"uplinkName,omitempty"`
	// NodeName is the node this state belongs to.
	NodeName *string `json:"nodeName,omitempty"`
}

// UplinkStateSpecApplyConfiguration constructs a declarative configuration of the UplinkStateSpec type for use with
// apply.
func UplinkStateSpec() *UplinkStateSpecApplyConfiguration {
	return &UplinkStateSpecApplyConfiguration{}
}

// WithUplinkName sets the UplinkName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UplinkName field is set to the value of the last call.
func (b *UplinkStateSpecApplyConfiguration) WithUplinkName(value string) *UplinkStateSpecApplyConfiguration {
	b.UplinkName = &value
	return b
}

// WithNodeName sets the NodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeName field is set to the value of the last call.
func (b *UplinkStateSpecApplyConfiguration) WithNodeName(value string) *UplinkStateSpecApplyConfiguration {
	b.NodeName = &value
	return b
}
