// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	vtepv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/vtep/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VTEPLister helps list VTEPs.
// All objects returned here must be treated as read-only.
type VTEPLister interface {
	// List lists all VTEPs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vtepv1.VTEP, err error)
	// Get retrieves the VTEP from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*vtepv1.VTEP, error)
	VTEPListerExpansion
}

// vTEPLister implements the VTEPLister interface.
type vTEPLister struct {
	listers.ResourceIndexer[*vtepv1.VTEP]
}

// NewVTEPLister returns a new VTEPLister.
func NewVTEPLister(indexer cache.Indexer) VTEPLister {
	return &vTEPLister{listers.New[*vtepv1.VTEP](indexer, vtepv1.Resource("vtep"))}
}
