/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	clusternetworkconnectv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/clusternetworkconnect/v1"
	types "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/types"
)

// ClusterNetworkConnectSpecApplyConfiguration represents a declarative configuration of the ClusterNetworkConnectSpec type for use
// with apply.
//
// ClusterNetworkConnectSpec defines the desired state of ClusterNetworkConnect.
type ClusterNetworkConnectSpecApplyConfiguration struct {
	// networkSelectors selects the networks to be connected together.
	// This can match User Defined Networks (UDNs) and/or Cluster User Defined Networks (CUDNs).
	// Only ClusterUserDefinedNetworkSelector and PrimaryUserDefinedNetworkSelector can be selected.
	NetworkSelectors *types.NetworkSelectors `json:"networkSelectors,omitempty"`
	// connectSubnets specifies the subnets used for interconnecting the selected networks.
	// This creates a shared subnet space that connected networks can use to communicate.
	// Can have at most 1 CIDR for each IP family (IPv4 and IPv6).
	// Must not overlap with:
	// any of the pod subnets used by the selected networks.
	// any of the transit subnets used by the selected networks.
	// any of the service CIDR range used in the cluster.
	// any of the join subnet of the selected networks to be connected.
	// any of the masquerade subnet range used in the cluster.
	// any of the node subnets chosen by the platform.
	// any of other connect subnets for other ClusterNetworkConnects that might be selecting same networks.
	//
	// Does not have a default value for the above reason so
	// that user takes care in setting non-overlapping subnets.
	ConnectSubnets []ConnectSubnetApplyConfiguration `json:"connectSubnets,omitempty"`
	// connectivity specifies which connectivity types should be enabled for the connected networks.
	Connectivity []clusternetworkconnectv1.ConnectivityType `json:"connectivity,omitempty"`
}

// ClusterNetworkConnectSpecApplyConfiguration constructs a declarative configuration of the ClusterNetworkConnectSpec type for use with
// apply.
func ClusterNetworkConnectSpec() *ClusterNetworkConnectSpecApplyConfiguration {
	return &ClusterNetworkConnectSpecApplyConfiguration{}
}

// WithNetworkSelectors sets the NetworkSelectors field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkSelectors field is set to the value of the last call.
func (b *ClusterNetworkConnectSpecApplyConfiguration) WithNetworkSelectors(value types.NetworkSelectors) *ClusterNetworkConnectSpecApplyConfiguration {
	b.NetworkSelectors = &value
	return b
}

// WithConnectSubnets adds the given value to the ConnectSubnets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ConnectSubnets field.
func (b *ClusterNetworkConnectSpecApplyConfiguration) WithConnectSubnets(values ...*ConnectSubnetApplyConfiguration) *ClusterNetworkConnectSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConnectSubnets")
		}
		b.ConnectSubnets = append(b.ConnectSubnets, *values[i])
	}
	return b
}

// WithConnectivity adds the given value to the Connectivity field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Connectivity field.
func (b *ClusterNetworkConnectSpecApplyConfiguration) WithConnectivity(values ...clusternetworkconnectv1.ConnectivityType) *ClusterNetworkConnectSpecApplyConfiguration {
	for i := range values {
		b.Connectivity = append(b.Connectivity, values[i])
	}
	return b
}
