// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	clusternetworkconnectv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/clusternetworkconnect/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterNetworkConnectStatusApplyConfiguration represents a declarative configuration of the ClusterNetworkConnectStatus type for use
// with apply.
//
// ClusterNetworkConnectStatus defines the observed state of ClusterNetworkConnect.
type ClusterNetworkConnectStatusApplyConfiguration struct {
	// status is a concise indication of whether the ClusterNetworkConnect
	// resource is applied with success.
	Status *clusternetworkconnectv1.StatusType `json:"status,omitempty"`
	// conditions is an array of condition objects indicating details about
	// status of ClusterNetworkConnect object.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ClusterNetworkConnectStatusApplyConfiguration constructs a declarative configuration of the ClusterNetworkConnectStatus type for use with
// apply.
func ClusterNetworkConnectStatus() *ClusterNetworkConnectStatusApplyConfiguration {
	return &ClusterNetworkConnectStatusApplyConfiguration{}
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *ClusterNetworkConnectStatusApplyConfiguration) WithStatus(value clusternetworkconnectv1.StatusType) *ClusterNetworkConnectStatusApplyConfiguration {
	b.Status = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ClusterNetworkConnectStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *ClusterNetworkConnectStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
