// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/clusternetworkconnect/v1"
	clusternetworkconnectv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/clusternetworkconnect/v1/apis/applyconfiguration/clusternetworkconnect/v1"
	typedclusternetworkconnectv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/clusternetworkconnect/v1/apis/clientset/versioned/typed/clusternetworkconnect/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterNetworkConnects implements ClusterNetworkConnectInterface
type fakeClusterNetworkConnects struct {
	*gentype.FakeClientWithListAndApply[*v1.ClusterNetworkConnect, *v1.ClusterNetworkConnectList, *clusternetworkconnectv1.ClusterNetworkConnectApplyConfiguration]
	Fake *FakeK8sV1
}

func newFakeClusterNetworkConnects(fake *FakeK8sV1) typedclusternetworkconnectv1.ClusterNetworkConnectInterface {
	return &fakeClusterNetworkConnects{
		gentype.NewFakeClientWithListAndApply[*v1.ClusterNetworkConnect, *v1.ClusterNetworkConnectList, *clusternetworkconnectv1.ClusterNetworkConnectApplyConfiguration](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("clusternetworkconnects"),
			v1.SchemeGroupVersion.WithKind("ClusterNetworkConnect"),
			func() *v1.ClusterNetworkConnect { return &v1.ClusterNetworkConnect{} },
			func() *v1.ClusterNetworkConnectList { return &v1.ClusterNetworkConnectList{} },
			func(dst, src *v1.ClusterNetworkConnectList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ClusterNetworkConnectList) []*v1.ClusterNetworkConnect {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.ClusterNetworkConnectList, items []*v1.ClusterNetworkConnect) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
