// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// EgressServiceStatusApplyConfiguration represents a declarative configuration of the EgressServiceStatus type for use
// with apply.
//
// EgressServiceStatus defines the observed state of EgressService
type EgressServiceStatusApplyConfiguration struct {
	// The name of the node selected to handle the service's traffic.
	// In case sourceIPBy=Network the field will be set to "ALL".
	Host *string `json:"host,omitempty"`
}

// EgressServiceStatusApplyConfiguration constructs a declarative configuration of the EgressServiceStatus type for use with
// apply.
func EgressServiceStatus() *EgressServiceStatusApplyConfiguration {
	return &EgressServiceStatusApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *EgressServiceStatusApplyConfiguration) WithHost(value string) *EgressServiceStatusApplyConfiguration {
	b.Host = &value
	return b
}
