/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	egressservicev1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressservice/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// EgressServiceSpecApplyConfiguration represents a declarative configuration of the EgressServiceSpec type for use
// with apply.
//
// EgressServiceSpec defines the desired state of EgressService
type EgressServiceSpecApplyConfiguration struct {
	// Determines the source IP of egress traffic originating from the pods backing the LoadBalancer Service.
	// When `LoadBalancerIP` the source IP is set to its LoadBalancer ingress IP.
	// When `Network` the source IP is set according to the interface of the Network,
	// leveraging the masquerade rules that are already in place.
	// Typically these rules specify SNAT to the IP of the outgoing interface,
	// which means the packet will typically leave with the IP of the node.
	SourceIPBy *egressservicev1.SourceIPMode `json:"sourceIPBy,omitempty"`
	// Allows limiting the nodes that can be selected to handle the service's traffic when sourceIPBy=LoadBalancerIP.
	// When present only a node whose labels match the specified selectors can be selected
	// for handling the service's traffic.
	// When it is not specified any node in the cluster can be chosen to manage the service's traffic.
	NodeSelector *metav1.LabelSelectorApplyConfiguration `json:"nodeSelector,omitempty"`
	// The network which this service should send egress and corresponding ingress replies to.
	// This is typically implemented as VRF mapping, representing a numeric id or string name
	// of a routing table which by omission uses the default host routing.
	Network *string `json:"network,omitempty"`
}

// EgressServiceSpecApplyConfiguration constructs a declarative configuration of the EgressServiceSpec type for use with
// apply.
func EgressServiceSpec() *EgressServiceSpecApplyConfiguration {
	return &EgressServiceSpecApplyConfiguration{}
}

// WithSourceIPBy sets the SourceIPBy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceIPBy field is set to the value of the last call.
func (b *EgressServiceSpecApplyConfiguration) WithSourceIPBy(value egressservicev1.SourceIPMode) *EgressServiceSpecApplyConfiguration {
	b.SourceIPBy = &value
	return b
}

// WithNodeSelector sets the NodeSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeSelector field is set to the value of the last call.
func (b *EgressServiceSpecApplyConfiguration) WithNodeSelector(value *metav1.LabelSelectorApplyConfiguration) *EgressServiceSpecApplyConfiguration {
	b.NodeSelector = value
	return b
}

// WithNetwork sets the Network field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Network field is set to the value of the last call.
func (b *EgressServiceSpecApplyConfiguration) WithNetwork(value string) *EgressServiceSpecApplyConfiguration {
	b.Network = &value
	return b
}
