// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

import "github.com/ovn-kubernetes/libovsdb/model"

const NetworkFunctionHealthCheckTable = "Network_Function_Health_Check"

// NetworkFunctionHealthCheck defines an object in Network_Function_Health_Check table
type NetworkFunctionHealthCheck struct {
	UUID        string            `ovsdb:"_uuid"`
	ExternalIDs map[string]string `ovsdb:"external_ids"`
	Name        string            `ovsdb:"name"`
	Options     map[string]string `ovsdb:"options"`
}

func (a *NetworkFunctionHealthCheck) GetUUID() string {
	return a.UUID
}

func (a *NetworkFunctionHealthCheck) GetExternalIDs() map[string]string {
	return a.ExternalIDs
}

func copyNetworkFunctionHealthCheckExternalIDs(a map[string]string) map[string]string {
	if a == nil {
		return nil
	}
	b := make(map[string]string, len(a))
	for k, v := range a {
		b[k] = v
	}
	return b
}

func equalNetworkFunctionHealthCheckExternalIDs(a, b map[string]string) bool {
	if (a == nil) != (b == nil) {
		return false
	}
	if len(a) != len(b) {
		return false
	}
	for k, v := range a {
		if w, ok := b[k]; !ok || v != w {
			return false
		}
	}
	return true
}

func (a *NetworkFunctionHealthCheck) GetName() string {
	return a.Name
}

func (a *NetworkFunctionHealthCheck) GetOptions() map[string]string {
	return a.Options
}

func copyNetworkFunctionHealthCheckOptions(a map[string]string) map[string]string {
	if a == nil {
		return nil
	}
	b := make(map[string]string, len(a))
	for k, v := range a {
		b[k] = v
	}
	return b
}

func equalNetworkFunctionHealthCheckOptions(a, b map[string]string) bool {
	if (a == nil) != (b == nil) {
		return false
	}
	if len(a) != len(b) {
		return false
	}
	for k, v := range a {
		if w, ok := b[k]; !ok || v != w {
			return false
		}
	}
	return true
}

func (a *NetworkFunctionHealthCheck) DeepCopyInto(b *NetworkFunctionHealthCheck) {
	*b = *a
	b.ExternalIDs = copyNetworkFunctionHealthCheckExternalIDs(a.ExternalIDs)
	b.Options = copyNetworkFunctionHealthCheckOptions(a.Options)
}

func (a *NetworkFunctionHealthCheck) DeepCopy() *NetworkFunctionHealthCheck {
	b := new(NetworkFunctionHealthCheck)
	a.DeepCopyInto(b)
	return b
}

func (a *NetworkFunctionHealthCheck) CloneModelInto(b model.Model) {
	c := b.(*NetworkFunctionHealthCheck)
	a.DeepCopyInto(c)
}

func (a *NetworkFunctionHealthCheck) CloneModel() model.Model {
	return a.DeepCopy()
}

func (a *NetworkFunctionHealthCheck) Equals(b *NetworkFunctionHealthCheck) bool {
	return a.UUID == b.UUID &&
		equalNetworkFunctionHealthCheckExternalIDs(a.ExternalIDs, b.ExternalIDs) &&
		a.Name == b.Name &&
		equalNetworkFunctionHealthCheckOptions(a.Options, b.Options)
}

func (a *NetworkFunctionHealthCheck) EqualsModel(b model.Model) bool {
	c := b.(*NetworkFunctionHealthCheck)
	return a.Equals(c)
}

var _ model.CloneableModel = &NetworkFunctionHealthCheck{}
var _ model.ComparableModel = &NetworkFunctionHealthCheck{}
