// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

import "github.com/ovn-kubernetes/libovsdb/model"

const NetworkFunctionTable = "Network_Function"

// NetworkFunction defines an object in Network_Function table
type NetworkFunction struct {
	UUID        string            `ovsdb:"_uuid"`
	ExternalIDs map[string]string `ovsdb:"external_ids"`
	HealthCheck *string           `ovsdb:"health_check"`
	ID          int               `ovsdb:"id"`
	Inport      string            `ovsdb:"inport"`
	Name        string            `ovsdb:"name"`
	Outport     string            `ovsdb:"outport"`
}

func (a *NetworkFunction) GetUUID() string {
	return a.UUID
}

func (a *NetworkFunction) GetExternalIDs() map[string]string {
	return a.ExternalIDs
}

func copyNetworkFunctionExternalIDs(a map[string]string) map[string]string {
	if a == nil {
		return nil
	}
	b := make(map[string]string, len(a))
	for k, v := range a {
		b[k] = v
	}
	return b
}

func equalNetworkFunctionExternalIDs(a, b map[string]string) bool {
	if (a == nil) != (b == nil) {
		return false
	}
	if len(a) != len(b) {
		return false
	}
	for k, v := range a {
		if w, ok := b[k]; !ok || v != w {
			return false
		}
	}
	return true
}

func (a *NetworkFunction) GetHealthCheck() *string {
	return a.HealthCheck
}

func copyNetworkFunctionHealthCheck(a *string) *string {
	if a == nil {
		return nil
	}
	b := *a
	return &b
}

func equalNetworkFunctionHealthCheck(a, b *string) bool {
	if (a == nil) != (b == nil) {
		return false
	}
	if a == b {
		return true
	}
	return *a == *b
}

func (a *NetworkFunction) GetID() int {
	return a.ID
}

func (a *NetworkFunction) GetInport() string {
	return a.Inport
}

func (a *NetworkFunction) GetName() string {
	return a.Name
}

func (a *NetworkFunction) GetOutport() string {
	return a.Outport
}

func (a *NetworkFunction) DeepCopyInto(b *NetworkFunction) {
	*b = *a
	b.ExternalIDs = copyNetworkFunctionExternalIDs(a.ExternalIDs)
	b.HealthCheck = copyNetworkFunctionHealthCheck(a.HealthCheck)
}

func (a *NetworkFunction) DeepCopy() *NetworkFunction {
	b := new(NetworkFunction)
	a.DeepCopyInto(b)
	return b
}

func (a *NetworkFunction) CloneModelInto(b model.Model) {
	c := b.(*NetworkFunction)
	a.DeepCopyInto(c)
}

func (a *NetworkFunction) CloneModel() model.Model {
	return a.DeepCopy()
}

func (a *NetworkFunction) Equals(b *NetworkFunction) bool {
	return a.UUID == b.UUID &&
		equalNetworkFunctionExternalIDs(a.ExternalIDs, b.ExternalIDs) &&
		equalNetworkFunctionHealthCheck(a.HealthCheck, b.HealthCheck) &&
		a.ID == b.ID &&
		a.Inport == b.Inport &&
		a.Name == b.Name &&
		a.Outport == b.Outport
}

func (a *NetworkFunction) EqualsModel(b model.Model) bool {
	c := b.(*NetworkFunction)
	return a.Equals(c)
}

var _ model.CloneableModel = &NetworkFunction{}
var _ model.ComparableModel = &NetworkFunction{}
