// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AdminPolicyBasedExternalRouteSpecApplyConfiguration represents a declarative configuration of the AdminPolicyBasedExternalRouteSpec type for use
// with apply.
//
// AdminPolicyBasedExternalRouteSpec defines the desired state of AdminPolicyBasedExternalRoute
type AdminPolicyBasedExternalRouteSpecApplyConfiguration struct {
	// From defines the selectors that will determine the target namespaces to this CR.
	From *ExternalNetworkSourceApplyConfiguration `json:"from,omitempty"`
	// NextHops defines two types of hops: Static and Dynamic. Each hop defines at least one external gateway IP.
	NextHops *ExternalNextHopsApplyConfiguration `json:"nextHops,omitempty"`
}

// AdminPolicyBasedExternalRouteSpecApplyConfiguration constructs a declarative configuration of the AdminPolicyBasedExternalRouteSpec type for use with
// apply.
func AdminPolicyBasedExternalRouteSpec() *AdminPolicyBasedExternalRouteSpecApplyConfiguration {
	return &AdminPolicyBasedExternalRouteSpecApplyConfiguration{}
}

// WithFrom sets the From field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the From field is set to the value of the last call.
func (b *AdminPolicyBasedExternalRouteSpecApplyConfiguration) WithFrom(value *ExternalNetworkSourceApplyConfiguration) *AdminPolicyBasedExternalRouteSpecApplyConfiguration {
	b.From = value
	return b
}

// WithNextHops sets the NextHops field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NextHops field is set to the value of the last call.
func (b *AdminPolicyBasedExternalRouteSpecApplyConfiguration) WithNextHops(value *ExternalNextHopsApplyConfiguration) *AdminPolicyBasedExternalRouteSpecApplyConfiguration {
	b.NextHops = value
	return b
}
