// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	adminpolicybasedroutev1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/adminpolicybasedroute/v1"
	internal "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/adminpolicybasedroute/v1/apis/applyconfiguration/internal"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// AdminPolicyBasedExternalRouteApplyConfiguration represents a declarative configuration of the AdminPolicyBasedExternalRoute type for use
// with apply.
//
// AdminPolicyBasedExternalRoute is a CRD allowing the cluster administrators to configure policies for external gateway IPs to be applied to all the pods contained in selected namespaces.
// Egress traffic from the pods that belong to the selected namespaces to outside the cluster is routed through these external gateway IPs.
type AdminPolicyBasedExternalRouteApplyConfiguration struct {
	metav1.TypeMetaApplyConfiguration    `json:",inline"`
	*metav1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                                 *AdminPolicyBasedExternalRouteSpecApplyConfiguration `json:"spec,omitempty"`
	Status                               *AdminPolicyBasedRouteStatusApplyConfiguration       `json:"status,omitempty"`
}

// AdminPolicyBasedExternalRoute constructs a declarative configuration of the AdminPolicyBasedExternalRoute type for use with
// apply.
func AdminPolicyBasedExternalRoute(name string) *AdminPolicyBasedExternalRouteApplyConfiguration {
	b := &AdminPolicyBasedExternalRouteApplyConfiguration{}
	b.WithName(name)
	b.WithKind("AdminPolicyBasedExternalRoute")
	b.WithAPIVersion("k8s.ovn.org/v1")
	return b
}

// ExtractAdminPolicyBasedExternalRouteFrom extracts the applied configuration owned by fieldManager from
// adminPolicyBasedExternalRoute for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// adminPolicyBasedExternalRoute must be a unmodified AdminPolicyBasedExternalRoute API object that was retrieved from the Kubernetes API.
// ExtractAdminPolicyBasedExternalRouteFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractAdminPolicyBasedExternalRouteFrom(adminPolicyBasedExternalRoute *adminpolicybasedroutev1.AdminPolicyBasedExternalRoute, fieldManager string, subresource string) (*AdminPolicyBasedExternalRouteApplyConfiguration, error) {
	b := &AdminPolicyBasedExternalRouteApplyConfiguration{}
	err := managedfields.ExtractInto(adminPolicyBasedExternalRoute, internal.Parser().Type("com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.adminpolicybasedroute.v1.AdminPolicyBasedExternalRoute"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(adminPolicyBasedExternalRoute.Name)

	b.WithKind("AdminPolicyBasedExternalRoute")
	b.WithAPIVersion("k8s.ovn.org/v1")
	return b, nil
}

// ExtractAdminPolicyBasedExternalRoute extracts the applied configuration owned by fieldManager from
// adminPolicyBasedExternalRoute. If no managedFields are found in adminPolicyBasedExternalRoute for fieldManager, a
// AdminPolicyBasedExternalRouteApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// adminPolicyBasedExternalRoute must be a unmodified AdminPolicyBasedExternalRoute API object that was retrieved from the Kubernetes API.
// ExtractAdminPolicyBasedExternalRoute provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractAdminPolicyBasedExternalRoute(adminPolicyBasedExternalRoute *adminpolicybasedroutev1.AdminPolicyBasedExternalRoute, fieldManager string) (*AdminPolicyBasedExternalRouteApplyConfiguration, error) {
	return ExtractAdminPolicyBasedExternalRouteFrom(adminPolicyBasedExternalRoute, fieldManager, "")
}

// ExtractAdminPolicyBasedExternalRouteStatus extracts the applied configuration owned by fieldManager from
// adminPolicyBasedExternalRoute for the status subresource.
func ExtractAdminPolicyBasedExternalRouteStatus(adminPolicyBasedExternalRoute *adminpolicybasedroutev1.AdminPolicyBasedExternalRoute, fieldManager string) (*AdminPolicyBasedExternalRouteApplyConfiguration, error) {
	return ExtractAdminPolicyBasedExternalRouteFrom(adminPolicyBasedExternalRoute, fieldManager, "status")
}

func (b AdminPolicyBasedExternalRouteApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) WithKind(value string) *AdminPolicyBasedExternalRouteApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) WithAPIVersion(value string) *AdminPolicyBasedExternalRouteApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) WithName(value string) *AdminPolicyBasedExternalRouteApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) WithGenerateName(value string) *AdminPolicyBasedExternalRouteApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) WithNamespace(value string) *AdminPolicyBasedExternalRouteApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) WithUID(value types.UID) *AdminPolicyBasedExternalRouteApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) WithResourceVersion(value string) *AdminPolicyBasedExternalRouteApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) WithGeneration(value int64) *AdminPolicyBasedExternalRouteApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) WithCreationTimestamp(value apismetav1.Time) *AdminPolicyBasedExternalRouteApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) WithDeletionTimestamp(value apismetav1.Time) *AdminPolicyBasedExternalRouteApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *AdminPolicyBasedExternalRouteApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) WithLabels(entries map[string]string) *AdminPolicyBasedExternalRouteApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) WithAnnotations(entries map[string]string) *AdminPolicyBasedExternalRouteApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) WithOwnerReferences(values ...*metav1.OwnerReferenceApplyConfiguration) *AdminPolicyBasedExternalRouteApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) WithFinalizers(values ...string) *AdminPolicyBasedExternalRouteApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *AdminPolicyBasedExternalRouteApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &metav1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) WithSpec(value *AdminPolicyBasedExternalRouteSpecApplyConfiguration) *AdminPolicyBasedExternalRouteApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) WithStatus(value *AdminPolicyBasedRouteStatusApplyConfiguration) *AdminPolicyBasedExternalRouteApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *AdminPolicyBasedExternalRouteApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
