// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// StaticHopApplyConfiguration represents a declarative configuration of the StaticHop type for use
// with apply.
//
// StaticHop defines the configuration of a static IP that acts as an external Gateway Interface. IP field is mandatory.
type StaticHopApplyConfiguration struct {
	// IP defines the static IP to be used for egress traffic. The IP can be either IPv4 or IPv6.
	IP *string `json:"ip,omitempty"`
	// BFDEnabled determines if the interface implements the Bidirectional Forward Detection protocol. Defaults to false.
	BFDEnabled *bool `json:"bfdEnabled,omitempty"`
}

// StaticHopApplyConfiguration constructs a declarative configuration of the StaticHop type for use with
// apply.
func StaticHop() *StaticHopApplyConfiguration {
	return &StaticHopApplyConfiguration{}
}

// WithIP sets the IP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IP field is set to the value of the last call.
func (b *StaticHopApplyConfiguration) WithIP(value string) *StaticHopApplyConfiguration {
	b.IP = &value
	return b
}

// WithBFDEnabled sets the BFDEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BFDEnabled field is set to the value of the last call.
func (b *StaticHopApplyConfiguration) WithBFDEnabled(value bool) *StaticHopApplyConfiguration {
	b.BFDEnabled = &value
	return b
}
