/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/udnnode/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// UDNNodeLister helps list UDNNodes.
// All objects returned here must be treated as read-only.
type UDNNodeLister interface {
	// List lists all UDNNodes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.UDNNode, err error)
	// Get retrieves the UDNNode from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.UDNNode, error)
	UDNNodeListerExpansion
}

// uDNNodeLister implements the UDNNodeLister interface.
type uDNNodeLister struct {
	listers.ResourceIndexer[*v1.UDNNode]
}

// NewUDNNodeLister returns a new UDNNodeLister.
func NewUDNNodeLister(indexer cache.Indexer) UDNNodeLister {
	return &uDNNodeLister{listers.New[*v1.UDNNode](indexer, v1.Resource("udnnode"))}
}
