// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// EgressQoSSpecApplyConfiguration represents a declarative configuration of the EgressQoSSpec type for use
// with apply.
//
// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// EgressQoSSpec defines the desired state of EgressQoS
type EgressQoSSpecApplyConfiguration struct {
	// a collection of Egress QoS rule objects
	Egress []EgressQoSRuleApplyConfiguration `json:"egress,omitempty"`
}

// EgressQoSSpecApplyConfiguration constructs a declarative configuration of the EgressQoSSpec type for use with
// apply.
func EgressQoSSpec() *EgressQoSSpecApplyConfiguration {
	return &EgressQoSSpecApplyConfiguration{}
}

// WithEgress adds the given value to the Egress field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Egress field.
func (b *EgressQoSSpecApplyConfiguration) WithEgress(values ...*EgressQoSRuleApplyConfiguration) *EgressQoSSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEgress")
		}
		b.Egress = append(b.Egress, *values[i])
	}
	return b
}
