// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// EgressQoSRuleApplyConfiguration represents a declarative configuration of the EgressQoSRule type for use
// with apply.
type EgressQoSRuleApplyConfiguration struct {
	// DSCP marking value for matching pods' traffic.
	DSCP *int `json:"dscp,omitempty"`
	// DstCIDR specifies the destination's CIDR. Only traffic heading
	// to this CIDR will be marked with the DSCP value.
	// This field is optional, and in case it is not set the rule is applied
	// to all egress traffic regardless of the destination.
	DstCIDR *string `json:"dstCIDR,omitempty"`
	// PodSelector applies the QoS rule only to the pods in the namespace whose label
	// matches this definition. This field is optional, and in case it is not set
	// results in the rule being applied to all pods in the namespace.
	PodSelector *metav1.LabelSelectorApplyConfiguration `json:"podSelector,omitempty"`
}

// EgressQoSRuleApplyConfiguration constructs a declarative configuration of the EgressQoSRule type for use with
// apply.
func EgressQoSRule() *EgressQoSRuleApplyConfiguration {
	return &EgressQoSRuleApplyConfiguration{}
}

// WithDSCP sets the DSCP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DSCP field is set to the value of the last call.
func (b *EgressQoSRuleApplyConfiguration) WithDSCP(value int) *EgressQoSRuleApplyConfiguration {
	b.DSCP = &value
	return b
}

// WithDstCIDR sets the DstCIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DstCIDR field is set to the value of the last call.
func (b *EgressQoSRuleApplyConfiguration) WithDstCIDR(value string) *EgressQoSRuleApplyConfiguration {
	b.DstCIDR = &value
	return b
}

// WithPodSelector sets the PodSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodSelector field is set to the value of the last call.
func (b *EgressQoSRuleApplyConfiguration) WithPodSelector(value *metav1.LabelSelectorApplyConfiguration) *EgressQoSRuleApplyConfiguration {
	b.PodSelector = value
	return b
}
