// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	clusternetworkconnectv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/clusternetworkconnect/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterNetworkConnectLister helps list ClusterNetworkConnects.
// All objects returned here must be treated as read-only.
type ClusterNetworkConnectLister interface {
	// List lists all ClusterNetworkConnects in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clusternetworkconnectv1.ClusterNetworkConnect, err error)
	// Get retrieves the ClusterNetworkConnect from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clusternetworkconnectv1.ClusterNetworkConnect, error)
	ClusterNetworkConnectListerExpansion
}

// clusterNetworkConnectLister implements the ClusterNetworkConnectLister interface.
type clusterNetworkConnectLister struct {
	listers.ResourceIndexer[*clusternetworkconnectv1.ClusterNetworkConnect]
}

// NewClusterNetworkConnectLister returns a new ClusterNetworkConnectLister.
func NewClusterNetworkConnectLister(indexer cache.Indexer) ClusterNetworkConnectLister {
	return &clusterNetworkConnectLister{listers.New[*clusternetworkconnectv1.ClusterNetworkConnect](indexer, clusternetworkconnectv1.Resource("clusternetworkconnect"))}
}
