// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

// ClusterNetworkConnectListerExpansion allows custom methods to be added to
// ClusterNetworkConnectLister.
type ClusterNetworkConnectListerExpansion interface{}
