// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	egressipv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressip/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// EgressIPLister helps list EgressIPs.
// All objects returned here must be treated as read-only.
type EgressIPLister interface {
	// List lists all EgressIPs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*egressipv1.EgressIP, err error)
	// Get retrieves the EgressIP from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*egressipv1.EgressIP, error)
	EgressIPListerExpansion
}

// egressIPLister implements the EgressIPLister interface.
type egressIPLister struct {
	listers.ResourceIndexer[*egressipv1.EgressIP]
}

// NewEgressIPLister returns a new EgressIPLister.
func NewEgressIPLister(indexer cache.Indexer) EgressIPLister {
	return &egressIPLister{listers.New[*egressipv1.EgressIP](indexer, egressipv1.Resource("egressip"))}
}
