// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

// EgressIPListerExpansion allows custom methods to be added to
// EgressIPLister.
type EgressIPListerExpansion interface{}
