// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	userdefinednetworkv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/userdefinednetwork/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterUserDefinedNetworkLister helps list ClusterUserDefinedNetworks.
// All objects returned here must be treated as read-only.
type ClusterUserDefinedNetworkLister interface {
	// List lists all ClusterUserDefinedNetworks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*userdefinednetworkv1.ClusterUserDefinedNetwork, err error)
	// Get retrieves the ClusterUserDefinedNetwork from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*userdefinednetworkv1.ClusterUserDefinedNetwork, error)
	ClusterUserDefinedNetworkListerExpansion
}

// clusterUserDefinedNetworkLister implements the ClusterUserDefinedNetworkLister interface.
type clusterUserDefinedNetworkLister struct {
	listers.ResourceIndexer[*userdefinednetworkv1.ClusterUserDefinedNetwork]
}

// NewClusterUserDefinedNetworkLister returns a new ClusterUserDefinedNetworkLister.
func NewClusterUserDefinedNetworkLister(indexer cache.Indexer) ClusterUserDefinedNetworkLister {
	return &clusterUserDefinedNetworkLister{listers.New[*userdefinednetworkv1.ClusterUserDefinedNetwork](indexer, userdefinednetworkv1.Resource("clusteruserdefinednetwork"))}
}
