name: Enhancing E2E Test Coverage
description: Provide supporting details for enhancements to our existing e2e test coverage
labels: area/e2e-testing
body:
  - type: textarea
    id: e2e-testing
    attributes:
      label: What would you like to see added/updated/deleted in our end-to-end tests?
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: true
