name: Flaking Test
description: Report flaky tests or jobs in OVN-Kubernetes CI
labels: kind/ci-flake
body:
  - type: textarea
    id: jobs
    attributes:
      label: Which jobs are flaking?
      description: |
        Please only use this template for submitting reports about flaky tests or jobs (pass or fail with no underlying change in code)in OVN-Kubernetes CI.
        Links to failed CI runs which show the specific failures in presubmit CI runs are appreciated.
        Is it shard, control-plane, dualstack, unit-tests etc?
    validations:
      required: true

  - type: textarea
    id: tests
    attributes:
      label: Which tests are flaking?
      description: |
        Please tell us the name of the tests that are flaking
    validations:
      required: true

  - type: textarea
    id: since
    attributes:
      label: Since when has it been flaking?
    validations:
      required: true

  # FIXME: When @jluhrsen get's us testspace grid link
  # uncomment this portion
  #- type: input
  #  id: testgrid
  #  attributes:
  #    label: Testgrid link
  #    description: |
  #      TBD: FIXME

  - type: textarea
    id: reason
    attributes:
      label: Reason for failure (if possible)

  - type: textarea
    id: additional
    attributes:
      label: Anything else we need to know?
