// Code generated by go-bindata. (@generated) DO NOT EDIT.

 //Package testdata generated by go-bindata.// sources:
// bindata.go
// networking/OWNERS
// networking/hello-pod-daemonset.yaml
// networking/hellosdn.yaml
// networking/networkpolicy/allow-egress-red.yaml
// networking/networkpolicy/allow-from-all-namespaces.yaml
// networking/networkpolicy/allow-from-same-namespace.yaml
// networking/networkpolicy/allow-ingress-red.yaml
// networking/networkpolicy/allow-same-namespace.yaml
// networking/networkpolicy/allow-to-openshift-dns.yaml
// networking/networkpolicy/allow-to-same-namespace.yaml
// networking/networkpolicy/default-allow-egress.yaml
// networking/networkpolicy/default-deny-egress.yaml
// networking/networkpolicy/default-deny-ingress.yaml
// networking/networkpolicy/egress-allow-all.yaml
// networking/networkpolicy/egress-ingress-62524.yaml
// networking/networkpolicy/egress_49696.yaml
// networking/networkpolicy/generic-networkpolicy-template.yaml
// networking/networkpolicy/ingress-allow-all.yaml
// networking/networkpolicy/ingress_49696.yaml
// networking/networkpolicy/ipblock/ipBlock-egress-dual-CIDRs-template.yaml
// networking/networkpolicy/ipblock/ipBlock-egress-dual-multiple-CIDRs-template.yaml
// networking/networkpolicy/ipblock/ipBlock-egress-except-dual-CIDRs-template.yaml
// networking/networkpolicy/ipblock/ipBlock-egress-except-single-CIDR-template.yaml
// networking/networkpolicy/ipblock/ipBlock-egress-single-CIDR-template.yaml
// networking/networkpolicy/ipblock/ipBlock-egress-single-multiple-CIDRs-template.yaml
// networking/networkpolicy/ipblock/ipBlock-ingress-dual-CIDRs-template.yaml
// networking/networkpolicy/ipblock/ipBlock-ingress-dual-multiple-CIDRs-template.yaml
// networking/networkpolicy/ipblock/ipBlock-ingress-single-CIDR-template.yaml
// networking/networkpolicy/ipblock/ipBlock-ingress-single-multiple-CIDRs-template.yaml
// networking/networkpolicy/netpol-30920-75540.yaml
// networking/networkpolicy/vap-npprotection-blockdeletion.yaml
// networking/ping-for-pod-specific-node-template.yaml
// networking/ping-for-pod-template.yaml
// networking/service-generic-template.yaml
// networking/statefulset-hello.yaml
// networking/testpod.yaml
package testdata

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)
type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

// Name return file name
func (fi bindataFileInfo) Name() string {
	return fi.name
}

// Size return file size
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}

// Mode return file mode
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}

// ModTime return file modify time
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}

// IsDir return file whether a directory
func (fi bindataFileInfo) IsDir() bool {
	return fi.mode&os.ModeDir != 0
}

// Sys return file is sys mode
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _bindataGo = []byte(``)

func bindataGoBytes() ([]byte, error) {
	return _bindataGo, nil
}

func bindataGo() (*asset, error) {
	bytes, err := bindataGoBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "bindata.go", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingOwners = []byte(`approvers:
  - zhaozhanqi
  - asood-rh
  - jechen0648
`)

func networkingOwnersBytes() ([]byte, error) {
	return _networkingOwners, nil
}

func networkingOwners() (*asset, error) {
	bytes, err := networkingOwnersBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/OWNERS", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingHelloPodDaemonsetYaml = []byte(`apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hello-daemonset
spec:
  selector:
    matchLabels:
      name: hello-pod
  template:
    metadata:
      labels:
        name: hello-pod
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - image: quay.io/openshifttest/hello-sdn@sha256:c89445416459e7adea9a5a416b3365ed3d74f2491beb904d61dc8d1eb89a72a4
        name: hello-pod
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
      terminationGracePeriodSeconds: 10
      tolerations:
      - operator: Exists

`)

func networkingHelloPodDaemonsetYamlBytes() ([]byte, error) {
	return _networkingHelloPodDaemonsetYaml, nil
}

func networkingHelloPodDaemonsetYaml() (*asset, error) {
	bytes, err := networkingHelloPodDaemonsetYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/hello-pod-daemonset.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingHellosdnYaml = []byte(`{
    "apiVersion": "v1",
    "kind": "List",
    "items": [
        {
            "apiVersion": "v1",
            "kind": "ReplicationController",
            "metadata": {
                "labels": {
                    "name": "hello-sdn"
                },
                "name": "hello-sdn"
            },
            "spec": {
                "replicas": 2,
                "template": {
                    "metadata": {
                        "labels": {
                            "name": "hellosdn"
                        }
                    },
                    "spec": {
                        "containers": [
                            {
                                "image": "quay.io/openshifttest/hello-sdn@sha256:c89445416459e7adea9a5a416b3365ed3d74f2491beb904d61dc8d1eb89a72a4",
                                "name": "hellosdn",
                                "imagePullPolicy": "IfNotPresent"
                            }
                        ]
                    }
                }
            }
        },
        {
            "apiVersion": "v1",
            "kind": "Service",
            "metadata": {
                "labels": {
                    "name": "hello-service"
                },
                "name": "hello-service"
            },
            "spec": {
                "ports": [
                    {
                        "name": "http",
                        "port": 27017,
                        "protocol": "TCP",
                        "targetPort": 8080
                    }
                ],
                "selector": {
                    "name": "hellosdn"
                }
            }
        }
    ]
}
`)

func networkingHellosdnYamlBytes() ([]byte, error) {
	return _networkingHellosdnYaml, nil
}

func networkingHellosdnYaml() (*asset, error) {
	bytes, err := networkingHellosdnYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/hellosdn.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyAllowEgressRedYaml = []byte(`apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-red
spec:
  podSelector: {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          team: qe
      podSelector:
        matchLabels:
          type: red
  policyTypes:
  - Egress
`)

func networkingNetworkpolicyAllowEgressRedYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyAllowEgressRedYaml, nil
}

func networkingNetworkpolicyAllowEgressRedYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyAllowEgressRedYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/allow-egress-red.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyAllowFromAllNamespacesYaml = []byte(`apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-all-namespaces
spec:
  podSelector: {}
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
      from:
        - namespaceSelector: {}
  policyTypes:
    - Ingress
`)

func networkingNetworkpolicyAllowFromAllNamespacesYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyAllowFromAllNamespacesYaml, nil
}

func networkingNetworkpolicyAllowFromAllNamespacesYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyAllowFromAllNamespacesYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/allow-from-all-namespaces.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyAllowFromSameNamespaceYaml = []byte(`apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-same-namespace
spec:
  ingress:
  - from:
    - podSelector: {}
  podSelector: {}
  policyTypes:
  - Ingress
`)

func networkingNetworkpolicyAllowFromSameNamespaceYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyAllowFromSameNamespaceYaml, nil
}

func networkingNetworkpolicyAllowFromSameNamespaceYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyAllowFromSameNamespaceYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/allow-from-same-namespace.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyAllowIngressRedYaml = []byte(`kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-ingress-to-red
spec:
  podSelector:
    matchLabels:
      type: red
  ingress:
  - {}
`)

func networkingNetworkpolicyAllowIngressRedYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyAllowIngressRedYaml, nil
}

func networkingNetworkpolicyAllowIngressRedYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyAllowIngressRedYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/allow-ingress-red.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyAllowSameNamespaceYaml = []byte(`apiVersion: networking.k8s.io/v1                                                               
kind: NetworkPolicy                                                                            
metadata:                                                                                      
  name: allow-same-namespace                                                                   
spec:                                                                                          
  egress:                                                                                      
  - to:                                                                                        
    - podSelector: {}                                                                          
  ingress:                                                                                     
  - from:                                                                                      
    - podSelector: {}                                                                          
  podSelector: {}                                                                              
  policyTypes:                                                                                 
  - Ingress                                                                                    
  - Egress 
`)

func networkingNetworkpolicyAllowSameNamespaceYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyAllowSameNamespaceYaml, nil
}

func networkingNetworkpolicyAllowSameNamespaceYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyAllowSameNamespaceYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/allow-same-namespace.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyAllowToOpenshiftDnsYaml = []byte(`apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-openshift-dns
spec:
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-dns
    ports:
    - port: 5353
      protocol: TCP
    - port: 5353
      protocol: UDP
  podSelector: {}
  policyTypes:
  - Egress

`)

func networkingNetworkpolicyAllowToOpenshiftDnsYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyAllowToOpenshiftDnsYaml, nil
}

func networkingNetworkpolicyAllowToOpenshiftDnsYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyAllowToOpenshiftDnsYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/allow-to-openshift-dns.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyAllowToSameNamespaceYaml = []byte(`apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-same-namespace
spec:
  egress:
  - to:
    - podSelector: {}
  podSelector: {}
  policyTypes:
  - Egress
`)

func networkingNetworkpolicyAllowToSameNamespaceYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyAllowToSameNamespaceYaml, nil
}

func networkingNetworkpolicyAllowToSameNamespaceYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyAllowToSameNamespaceYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/allow-to-same-namespace.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyDefaultAllowEgressYaml = []byte(`kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-allow-egress
spec:
  podSelector: {}
  egress:
    - {}
  policyTypes:
  - Egress

`)

func networkingNetworkpolicyDefaultAllowEgressYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyDefaultAllowEgressYaml, nil
}

func networkingNetworkpolicyDefaultAllowEgressYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyDefaultAllowEgressYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/default-allow-egress.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyDefaultDenyEgressYaml = []byte(`kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny-egress
spec:
  podSelector: {}
  policyTypes:
  - Egress
`)

func networkingNetworkpolicyDefaultDenyEgressYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyDefaultDenyEgressYaml, nil
}

func networkingNetworkpolicyDefaultDenyEgressYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyDefaultDenyEgressYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/default-deny-egress.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyDefaultDenyIngressYaml = []byte(`kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny-ingress
spec:
  podSelector: {}
  policyTypes:
  - Ingress
`)

func networkingNetworkpolicyDefaultDenyIngressYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyDefaultDenyIngressYaml, nil
}

func networkingNetworkpolicyDefaultDenyIngressYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyDefaultDenyIngressYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/default-deny-ingress.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyEgressAllowAllYaml = []byte(`kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-all-egress
spec:
  podSelector:
    matchLabels:
      name: test-pods
  egress:
    - {}
  policyTypes:
    - Egress
`)

func networkingNetworkpolicyEgressAllowAllYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyEgressAllowAllYaml, nil
}

func networkingNetworkpolicyEgressAllowAllYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyEgressAllowAllYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/egress-allow-all.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyEgressIngress62524Yaml = []byte(`apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-ingress-62524.test
spec:
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          team: openshift-networking
      podSelector:
        matchLabels:
          name: hello-pod
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          team: openshift-networking
      podSelector:
        matchLabels:
          name: test-pods
  podSelector:
    matchLabels:
      name: test-pods
  policyTypes:
  - Ingress
  - Egress
`)

func networkingNetworkpolicyEgressIngress62524YamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyEgressIngress62524Yaml, nil
}

func networkingNetworkpolicyEgressIngress62524Yaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyEgressIngress62524YamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/egress-ingress-62524.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyEgress_49696Yaml = []byte(`kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: egress-all-otherpod
spec:
  podSelector:
    matchLabels:
      name: hellosdn
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            team: openshift
  policyTypes:
    - Egress
`)

func networkingNetworkpolicyEgress_49696YamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyEgress_49696Yaml, nil
}

func networkingNetworkpolicyEgress_49696Yaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyEgress_49696YamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/egress_49696.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyGenericNetworkpolicyTemplateYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: generic_networkpolicy_template
objects:
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    name: "${NAME}"
    namespace: "${NAMESPACE}"
  spec:
    podSelector: {}
    "${POLICY}": 
    - "${DIRECTION1}":
         - podSelector : {}
           namespaceSelector: 
            "${NAMESPACESEL1}":
                 "${NAMESPACESELKEY1}": "${NAMESPACESELVAL1}"
    - "${DIRECTION2}":
         - podSelector : {}
           namespaceSelector: 
            "${NAMESPACESEL2}":
                 "${NAMESPACESELKEY2}": "${NAMESPACESELVAL2}"
    policyTypes:
    - "${POLICYTYPE}"
parameters:
- name: NAME 
- name: NAMESPACE
- name: POLICY
- name: DIRECTION1
- name: NAMESPACESEL1
- name: NAMESPACESELKEY1
- name: NAMESPACESELVAL1
- name: DIRECTION2
- name: NAMESPACESEL2
- name: NAMESPACESELKEY2
- name: NAMESPACESELVAL2
- name: POLICYTYPE
`)

func networkingNetworkpolicyGenericNetworkpolicyTemplateYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyGenericNetworkpolicyTemplateYaml, nil
}

func networkingNetworkpolicyGenericNetworkpolicyTemplateYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyGenericNetworkpolicyTemplateYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/generic-networkpolicy-template.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyIngressAllowAllYaml = []byte(`kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-all-ingress
spec:
  podSelector:
    matchLabels:
      name: hellosdn
  ingress:
    - {}
  policyTypes:
    - Ingress
`)

func networkingNetworkpolicyIngressAllowAllYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyIngressAllowAllYaml, nil
}

func networkingNetworkpolicyIngressAllowAllYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyIngressAllowAllYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/ingress-allow-all.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyIngress_49696Yaml = []byte(`kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-all-ingress
spec:
  podSelector:
    matchLabels:
      name: hellosdn
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            team: operations
        podSelector:
          matchLabels:
            name: test-pods
  policyTypes:
    - Ingress
`)

func networkingNetworkpolicyIngress_49696YamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyIngress_49696Yaml, nil
}

func networkingNetworkpolicyIngress_49696Yaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyIngress_49696YamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/ingress_49696.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyIpblockIpblockEgressDualCidrsTemplateYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ipBlock_egress_dual_cidrs_template
objects:
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    name: "${NAME}"
    namespace: "${NAMESPACE}"
  spec:
    podSelector: {}
    egress:
    - to:
      - ipBlock:
          cidr: "${cidrIpv4}"
      - ipBlock: 
          cidr: "${cidrIpv6}"
    policyTypes:
     - Egress
parameters:
- name: NAME  
- name: cidrIpv4
- name: cidrIpv6
- name: NAMESPACE
`)

func networkingNetworkpolicyIpblockIpblockEgressDualCidrsTemplateYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyIpblockIpblockEgressDualCidrsTemplateYaml, nil
}

func networkingNetworkpolicyIpblockIpblockEgressDualCidrsTemplateYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyIpblockIpblockEgressDualCidrsTemplateYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/ipblock/ipBlock-egress-dual-CIDRs-template.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyIpblockIpblockEgressDualMultipleCidrsTemplateYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ipBlockEgressDual_multiple_cidrs_template
objects:
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    name: "${NAME}"
    namespace: "${NAMESPACE}"
  spec:
    podSelector: {}
    egress:
    - to:
      - ipBlock:
          cidr: "${cidrIpv4}"
      - ipBlock:
          cidr: "${cidrIpv6}"
      - ipBlock:
          cidr: "${cidr2Ipv4}"
      - ipBlock:
          cidr: "${cidr2Ipv6}"
      - ipBlock:
          cidr: "${cidr3Ipv4}"
      - ipBlock:
          cidr: "${cidr3Ipv6}"
parameters:
- name: NAME
- name: cidrIpv4
- name: cidrIpv6
- name: cidr2Ipv4
- name: cidr2Ipv6
- name: cidr3Ipv4
- name: cidr3Ipv6
- name: NAMESPACE
`)

func networkingNetworkpolicyIpblockIpblockEgressDualMultipleCidrsTemplateYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyIpblockIpblockEgressDualMultipleCidrsTemplateYaml, nil
}

func networkingNetworkpolicyIpblockIpblockEgressDualMultipleCidrsTemplateYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyIpblockIpblockEgressDualMultipleCidrsTemplateYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/ipblock/ipBlock-egress-dual-multiple-CIDRs-template.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyIpblockIpblockEgressExceptDualCidrsTemplateYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ipBlock_egress_dual_cidrs_template
objects:
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    name: "${NAME}"
    namespace: "${NAMESPACE}"
  spec:
    podSelector: {}
    egress:
    - to:
      - ipBlock:
          cidr: "${CIDR_IPv4}"
          except:
          - "${EXCEPT_IPv4}"
      - ipBlock: 
          cidr: "${CIDR_IPv6}"
          except:
          - "${EXCEPT_IPv6}"
    policyTypes:
     - Egress
parameters:
- name: NAME  
- name: CIDR_IPv4
- name: CIDR_IPv6
- name: NAMESPACE
- name: EXCEPT_IPv4
- name: EXCEPT_IPv6
`)

func networkingNetworkpolicyIpblockIpblockEgressExceptDualCidrsTemplateYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyIpblockIpblockEgressExceptDualCidrsTemplateYaml, nil
}

func networkingNetworkpolicyIpblockIpblockEgressExceptDualCidrsTemplateYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyIpblockIpblockEgressExceptDualCidrsTemplateYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/ipblock/ipBlock-egress-except-dual-CIDRs-template.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyIpblockIpblockEgressExceptSingleCidrTemplateYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ipBlockEgressSingle_cidr_template
objects:
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    name: "${NAME}"
    namespace: "${NAMESPACE}"
  spec:
    podSelector: {}
    egress:
    - to:
      - ipBlock:
          cidr: "${CIDR}"
          except:
          - "${EXCEPT}"
    policyTypes:
     - Egress
parameters:
- name: NAME  
- name: CIDR
- name: NAMESPACE
- name: EXCEPT
`)

func networkingNetworkpolicyIpblockIpblockEgressExceptSingleCidrTemplateYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyIpblockIpblockEgressExceptSingleCidrTemplateYaml, nil
}

func networkingNetworkpolicyIpblockIpblockEgressExceptSingleCidrTemplateYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyIpblockIpblockEgressExceptSingleCidrTemplateYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/ipblock/ipBlock-egress-except-single-CIDR-template.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyIpblockIpblockEgressSingleCidrTemplateYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ipBlockEgressSingle_cidr_template
objects:
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    name: "${NAME}"
    namespace: "${NAMESPACE}"
  spec:
    podSelector: {}
    egress:
    - to:
      - ipBlock:
          cidr: "${CIDR}"
    policyTypes:
     - Egress
parameters:
- name: NAME  
- name: CIDR
- name: NAMESPACE
`)

func networkingNetworkpolicyIpblockIpblockEgressSingleCidrTemplateYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyIpblockIpblockEgressSingleCidrTemplateYaml, nil
}

func networkingNetworkpolicyIpblockIpblockEgressSingleCidrTemplateYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyIpblockIpblockEgressSingleCidrTemplateYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/ipblock/ipBlock-egress-single-CIDR-template.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyIpblockIpblockEgressSingleMultipleCidrsTemplateYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ipBlockEgressSingle_multiple_cidrs_template
objects:
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    name: "${NAME}"
    namespace: "${NAMESPACE}"
  spec:
    podSelector: {}
    egress:
    - to:
      - ipBlock:
          cidr: "${CIDR}"
      - ipBlock:
          cidr: "${CIDR2}"
      - ipBlock:
          cidr: "${CIDR3}"
parameters:
- name: NAME
- name: CIDR
- name: CIDR2
- name: CIDR3
- name: NAMESPACE
`)

func networkingNetworkpolicyIpblockIpblockEgressSingleMultipleCidrsTemplateYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyIpblockIpblockEgressSingleMultipleCidrsTemplateYaml, nil
}

func networkingNetworkpolicyIpblockIpblockEgressSingleMultipleCidrsTemplateYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyIpblockIpblockEgressSingleMultipleCidrsTemplateYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/ipblock/ipBlock-egress-single-multiple-CIDRs-template.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyIpblockIpblockIngressDualCidrsTemplateYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ipBlock_ingress_dual_cidrs_template
objects:
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    name: "${NAME}"
    namespace: "${NAMESPACE}"
  spec:
    podSelector: {}
    ingress:
    - from:
      - ipBlock:
          cidr: "${cidrIpv4}"
      - ipBlock: 
          cidr: "${cidrIpv6}"
parameters:
- name: NAME  
- name: cidrIpv4
- name: cidrIpv6
- name: NAMESPACE
`)

func networkingNetworkpolicyIpblockIpblockIngressDualCidrsTemplateYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyIpblockIpblockIngressDualCidrsTemplateYaml, nil
}

func networkingNetworkpolicyIpblockIpblockIngressDualCidrsTemplateYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyIpblockIpblockIngressDualCidrsTemplateYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/ipblock/ipBlock-ingress-dual-CIDRs-template.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyIpblockIpblockIngressDualMultipleCidrsTemplateYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ipBlock_ingress_dual_multiple_cidrs_template
objects:
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    name: "${NAME}"
    namespace: "${NAMESPACE}"
  spec:
    podSelector: {}
    ingress:
    - from:
      - ipBlock:
          cidr: "${cidrIpv4}"
      - ipBlock:
          cidr: "${cidrIpv6}"
      - ipBlock:
          cidr: "${cidr2Ipv4}"
      - ipBlock:
          cidr: "${cidr2Ipv6}"
      - ipBlock:
          cidr: "${cidr3Ipv4}"
      - ipBlock:
          cidr: "${cidr3Ipv6}"
parameters:
- name: NAME
- name: cidrIpv4
- name: cidrIpv6
- name: cidr2Ipv4
- name: cidr2Ipv6
- name: cidr3Ipv4
- name: cidr3Ipv6
- name: NAMESPACE
`)

func networkingNetworkpolicyIpblockIpblockIngressDualMultipleCidrsTemplateYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyIpblockIpblockIngressDualMultipleCidrsTemplateYaml, nil
}

func networkingNetworkpolicyIpblockIpblockIngressDualMultipleCidrsTemplateYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyIpblockIpblockIngressDualMultipleCidrsTemplateYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/ipblock/ipBlock-ingress-dual-multiple-CIDRs-template.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyIpblockIpblockIngressSingleCidrTemplateYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ipBlockIngressSingle_cidr_template
objects:
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    name: "${NAME}"
    namespace: "${NAMESPACE}"
  spec:
    podSelector: {}
    ingress:
    - from:
      - ipBlock:
          cidr: "${CIDR}"
parameters:
- name: NAME  
- name: CIDR
- name: NAMESPACE
`)

func networkingNetworkpolicyIpblockIpblockIngressSingleCidrTemplateYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyIpblockIpblockIngressSingleCidrTemplateYaml, nil
}

func networkingNetworkpolicyIpblockIpblockIngressSingleCidrTemplateYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyIpblockIpblockIngressSingleCidrTemplateYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/ipblock/ipBlock-ingress-single-CIDR-template.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyIpblockIpblockIngressSingleMultipleCidrsTemplateYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ipBlockIngressSingle_multiple_cidrs_template
objects:
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    name: "${NAME}"
    namespace: "${NAMESPACE}"
  spec:
    podSelector: {}
    ingress:
    - from:
      - ipBlock:
          cidr: "${CIDR}"
      - ipBlock:
          cidr: "${CIDR2}"
      - ipBlock:
          cidr: "${CIDR3}"
parameters:
- name: NAME
- name: CIDR
- name: CIDR2
- name: CIDR3
- name: NAMESPACE
`)

func networkingNetworkpolicyIpblockIpblockIngressSingleMultipleCidrsTemplateYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyIpblockIpblockIngressSingleMultipleCidrsTemplateYaml, nil
}

func networkingNetworkpolicyIpblockIpblockIngressSingleMultipleCidrsTemplateYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyIpblockIpblockIngressSingleMultipleCidrsTemplateYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/ipblock/ipBlock-ingress-single-multiple-CIDRs-template.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyNetpol3092075540Yaml = []byte(`apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: OCPBUGS-30920
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchExpressions:
        - key: name
          operator: In
          values:
          - invalid value
  podSelector: {}
  policyTypes:
  - Ingress
`)

func networkingNetworkpolicyNetpol3092075540YamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyNetpol3092075540Yaml, nil
}

func networkingNetworkpolicyNetpol3092075540Yaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyNetpol3092075540YamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/netpol-30920-75540.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingNetworkpolicyVapNpprotectionBlockdeletionYaml = []byte(`kind: ValidatingAdmissionPolicy
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: fine-grained-network-policy-protection
spec:
  matchConstraints:
    resourceRules:
      - operations:
          - DELETE
        apiGroups:
          - networking.k8s.io
        apiVersions:
          - v1
        resources:
          - networkpolicies
  validations:
    - expression: '!(has(oldObject.metadata.labels) && oldObject.metadata.labels[''npprotection/blockdeletion''] == "true")'
      message: "Cannot delete NetworkPolicy with 'npprotection/blockdeletion: true' label. This policy is not allowed for deletion."
---
kind: ValidatingAdmissionPolicyBinding
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: fine-grained-network-policy-protection-binding
spec:
  policyName: fine-grained-network-policy-protection
  validationActions:
    - Deny
`)

func networkingNetworkpolicyVapNpprotectionBlockdeletionYamlBytes() ([]byte, error) {
	return _networkingNetworkpolicyVapNpprotectionBlockdeletionYaml, nil
}

func networkingNetworkpolicyVapNpprotectionBlockdeletionYaml() (*asset, error) {
	bytes, err := networkingNetworkpolicyVapNpprotectionBlockdeletionYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/networkpolicy/vap-npprotection-blockdeletion.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingPingForPodSpecificNodeTemplateYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: hello-pod-specific-node-template
objects:
- kind: Pod
  apiVersion: v1
  metadata:
    name: "${NAME}"
    namespace: "${NAMESPACE}"
    labels:
      name: hello-pod
  spec:
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    containers:
    - image: "quay.io/openshifttest/hello-sdn@sha256:c89445416459e7adea9a5a416b3365ed3d74f2491beb904d61dc8d1eb89a72a4"
      name: hello-pod
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
    nodeName: "${NODENAME}"
parameters:
- name: NAME
- name: NAMESPACE
- name: NODENAME
`)

func networkingPingForPodSpecificNodeTemplateYamlBytes() ([]byte, error) {
	return _networkingPingForPodSpecificNodeTemplateYaml, nil
}

func networkingPingForPodSpecificNodeTemplateYaml() (*asset, error) {
	bytes, err := networkingPingForPodSpecificNodeTemplateYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/ping-for-pod-specific-node-template.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingPingForPodTemplateYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: hello-pod-template
objects:
- kind: Pod
  apiVersion: v1
  metadata:
    name: "${NAME}"
    namespace: "${NAMESPACE}"
    labels:
      name: hello-pod
  spec:
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    containers:
    - image: "quay.io/openshifttest/hello-sdn@sha256:c89445416459e7adea9a5a416b3365ed3d74f2491beb904d61dc8d1eb89a72a4"
      name: hello-pod
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
parameters:
- name: NAME
- name: NAMESPACE
`)

func networkingPingForPodTemplateYamlBytes() ([]byte, error) {
	return _networkingPingForPodTemplateYaml, nil
}

func networkingPingForPodTemplateYaml() (*asset, error) {
	bytes, err := networkingPingForPodTemplateYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/ping-for-pod-template.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingServiceGenericTemplateYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: test-service-template
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: "${SERVICENAME}"
    namespace: "${NAMESPACE}"
    labels:
      name: test-service
  spec:
    internalTrafficPolicy: "${internalTrafficPolicy}"
    externalTrafficPolicy: "${externalTrafficPolicy}"
    ipFamilyPolicy: "${ipFamilyPolicy}" 
    ports:
    - name: http
      port: 27017
      protocol: "${PROTOCOL}"
      targetPort: 8080
    selector:
      name: "${SELECTOR}"
    type: "${serviceType}"
parameters:
- name: SERVICENAME
- name: NAMESPACE
- name: internalTrafficPolicy
- name: externalTrafficPolicy
- name: ipFamilyPolicy
- name: PROTOCOL
- name: SELECTOR
- name: serviceType
- name: PORT
`)

func networkingServiceGenericTemplateYamlBytes() ([]byte, error) {
	return _networkingServiceGenericTemplateYaml, nil
}

func networkingServiceGenericTemplateYaml() (*asset, error) {
	bytes, err := networkingServiceGenericTemplateYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/service-generic-template.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingStatefulsetHelloYaml = []byte(`apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: hello
    name: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  serviceName: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: quay.io/openshifttest/hello-sdn@sha256:c89445416459e7adea9a5a416b3365ed3d74f2491beb904d61dc8d1eb89a72a4 
        name: hello
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        resources:
          limits:
            memory: 340Mi
      restartPolicy: Always
`)

func networkingStatefulsetHelloYamlBytes() ([]byte, error) {
	return _networkingStatefulsetHelloYaml, nil
}

func networkingStatefulsetHelloYaml() (*asset, error) {
	bytes, err := networkingStatefulsetHelloYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/statefulset-hello.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _networkingTestpodYaml = []byte(`{
    "apiVersion": "v1",
    "kind": "List",
    "items": [
        {
            "apiVersion": "v1",
            "kind": "ReplicationController",
            "metadata": {
                "labels": {
                    "name": "test-rc"
                },
                "name": "test-rc"
            },
            "spec": {
                "replicas": 2,
                "template": {
                    "metadata": {
                        "labels": {
                            "name": "test-pods"
                        }
                    },
                    "spec": {
                        "containers": [
                            {
                                "image": "quay.io/openshifttest/hello-sdn@sha256:c89445416459e7adea9a5a416b3365ed3d74f2491beb904d61dc8d1eb89a72a4",
                                "name": "test-pod",
                                "imagePullPolicy": "IfNotPresent"
                            }
                        ],
                        "tolerations": [
                            {
                                "effect": "NoSchedule",
                                "key": "node-role.kubernetes.io/outposts",
                                "operator": "Exists"
                            },
                            {
                                "effect": "NoSchedule",
                                "key": "node-role.kubernetes.io/edge",
                                "operator": "Exists"
                            }
                        ]
                    }
                }
            }
        },
        {
            "apiVersion": "v1",
            "kind": "Service",
            "metadata": {
                "labels": {
                    "name": "test-service"
                },
                "name": "test-service"
            },
            "spec": {
                "ports": [
                    {
                        "name": "http",
                        "port": 27017,
                        "protocol": "TCP",
                        "targetPort": 8080
                    }
                ],
                "selector": {
                    "name": "test-pods"
                }
            }
        }
    ]
}
`)

func networkingTestpodYamlBytes() ([]byte, error) {
	return _networkingTestpodYaml, nil
}

func networkingTestpodYaml() (*asset, error) {
	bytes, err := networkingTestpodYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "networking/testpod.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"bindata.go":                                                                           bindataGo,
	"networking/OWNERS":                                                                    networkingOwners,
	"networking/hello-pod-daemonset.yaml":                                                  networkingHelloPodDaemonsetYaml,
	"networking/hellosdn.yaml":                                                             networkingHellosdnYaml,
	"networking/networkpolicy/allow-egress-red.yaml":                                       networkingNetworkpolicyAllowEgressRedYaml,
	"networking/networkpolicy/allow-from-all-namespaces.yaml":                              networkingNetworkpolicyAllowFromAllNamespacesYaml,
	"networking/networkpolicy/allow-from-same-namespace.yaml":                              networkingNetworkpolicyAllowFromSameNamespaceYaml,
	"networking/networkpolicy/allow-ingress-red.yaml":                                      networkingNetworkpolicyAllowIngressRedYaml,
	"networking/networkpolicy/allow-same-namespace.yaml":                                   networkingNetworkpolicyAllowSameNamespaceYaml,
	"networking/networkpolicy/allow-to-openshift-dns.yaml":                                 networkingNetworkpolicyAllowToOpenshiftDnsYaml,
	"networking/networkpolicy/allow-to-same-namespace.yaml":                                networkingNetworkpolicyAllowToSameNamespaceYaml,
	"networking/networkpolicy/default-allow-egress.yaml":                                   networkingNetworkpolicyDefaultAllowEgressYaml,
	"networking/networkpolicy/default-deny-egress.yaml":                                    networkingNetworkpolicyDefaultDenyEgressYaml,
	"networking/networkpolicy/default-deny-ingress.yaml":                                   networkingNetworkpolicyDefaultDenyIngressYaml,
	"networking/networkpolicy/egress-allow-all.yaml":                                       networkingNetworkpolicyEgressAllowAllYaml,
	"networking/networkpolicy/egress-ingress-62524.yaml":                                   networkingNetworkpolicyEgressIngress62524Yaml,
	"networking/networkpolicy/egress_49696.yaml":                                           networkingNetworkpolicyEgress_49696Yaml,
	"networking/networkpolicy/generic-networkpolicy-template.yaml":                         networkingNetworkpolicyGenericNetworkpolicyTemplateYaml,
	"networking/networkpolicy/ingress-allow-all.yaml":                                      networkingNetworkpolicyIngressAllowAllYaml,
	"networking/networkpolicy/ingress_49696.yaml":                                          networkingNetworkpolicyIngress_49696Yaml,
	"networking/networkpolicy/ipblock/ipBlock-egress-dual-CIDRs-template.yaml":             networkingNetworkpolicyIpblockIpblockEgressDualCidrsTemplateYaml,
	"networking/networkpolicy/ipblock/ipBlock-egress-dual-multiple-CIDRs-template.yaml":    networkingNetworkpolicyIpblockIpblockEgressDualMultipleCidrsTemplateYaml,
	"networking/networkpolicy/ipblock/ipBlock-egress-except-dual-CIDRs-template.yaml":      networkingNetworkpolicyIpblockIpblockEgressExceptDualCidrsTemplateYaml,
	"networking/networkpolicy/ipblock/ipBlock-egress-except-single-CIDR-template.yaml":     networkingNetworkpolicyIpblockIpblockEgressExceptSingleCidrTemplateYaml,
	"networking/networkpolicy/ipblock/ipBlock-egress-single-CIDR-template.yaml":            networkingNetworkpolicyIpblockIpblockEgressSingleCidrTemplateYaml,
	"networking/networkpolicy/ipblock/ipBlock-egress-single-multiple-CIDRs-template.yaml":  networkingNetworkpolicyIpblockIpblockEgressSingleMultipleCidrsTemplateYaml,
	"networking/networkpolicy/ipblock/ipBlock-ingress-dual-CIDRs-template.yaml":            networkingNetworkpolicyIpblockIpblockIngressDualCidrsTemplateYaml,
	"networking/networkpolicy/ipblock/ipBlock-ingress-dual-multiple-CIDRs-template.yaml":   networkingNetworkpolicyIpblockIpblockIngressDualMultipleCidrsTemplateYaml,
	"networking/networkpolicy/ipblock/ipBlock-ingress-single-CIDR-template.yaml":           networkingNetworkpolicyIpblockIpblockIngressSingleCidrTemplateYaml,
	"networking/networkpolicy/ipblock/ipBlock-ingress-single-multiple-CIDRs-template.yaml": networkingNetworkpolicyIpblockIpblockIngressSingleMultipleCidrsTemplateYaml,
	"networking/networkpolicy/netpol-30920-75540.yaml":                                     networkingNetworkpolicyNetpol3092075540Yaml,
	"networking/networkpolicy/vap-npprotection-blockdeletion.yaml":                         networkingNetworkpolicyVapNpprotectionBlockdeletionYaml,
	"networking/ping-for-pod-specific-node-template.yaml":                                  networkingPingForPodSpecificNodeTemplateYaml,
	"networking/ping-for-pod-template.yaml":                                                networkingPingForPodTemplateYaml,
	"networking/service-generic-template.yaml":                                             networkingServiceGenericTemplateYaml,
	"networking/statefulset-hello.yaml":                                                    networkingStatefulsetHelloYaml,
	"networking/testpod.yaml":                                                              networkingTestpodYaml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"bindata.go": &bintree{bindataGo, map[string]*bintree{}},
	"networking": &bintree{nil, map[string]*bintree{
		"OWNERS":                   &bintree{networkingOwners, map[string]*bintree{}},
		"hello-pod-daemonset.yaml": &bintree{networkingHelloPodDaemonsetYaml, map[string]*bintree{}},
		"hellosdn.yaml":            &bintree{networkingHellosdnYaml, map[string]*bintree{}},
		"networkpolicy": &bintree{nil, map[string]*bintree{
			"allow-egress-red.yaml":               &bintree{networkingNetworkpolicyAllowEgressRedYaml, map[string]*bintree{}},
			"allow-from-all-namespaces.yaml":      &bintree{networkingNetworkpolicyAllowFromAllNamespacesYaml, map[string]*bintree{}},
			"allow-from-same-namespace.yaml":      &bintree{networkingNetworkpolicyAllowFromSameNamespaceYaml, map[string]*bintree{}},
			"allow-ingress-red.yaml":              &bintree{networkingNetworkpolicyAllowIngressRedYaml, map[string]*bintree{}},
			"allow-same-namespace.yaml":           &bintree{networkingNetworkpolicyAllowSameNamespaceYaml, map[string]*bintree{}},
			"allow-to-openshift-dns.yaml":         &bintree{networkingNetworkpolicyAllowToOpenshiftDnsYaml, map[string]*bintree{}},
			"allow-to-same-namespace.yaml":        &bintree{networkingNetworkpolicyAllowToSameNamespaceYaml, map[string]*bintree{}},
			"default-allow-egress.yaml":           &bintree{networkingNetworkpolicyDefaultAllowEgressYaml, map[string]*bintree{}},
			"default-deny-egress.yaml":            &bintree{networkingNetworkpolicyDefaultDenyEgressYaml, map[string]*bintree{}},
			"default-deny-ingress.yaml":           &bintree{networkingNetworkpolicyDefaultDenyIngressYaml, map[string]*bintree{}},
			"egress-allow-all.yaml":               &bintree{networkingNetworkpolicyEgressAllowAllYaml, map[string]*bintree{}},
			"egress-ingress-62524.yaml":           &bintree{networkingNetworkpolicyEgressIngress62524Yaml, map[string]*bintree{}},
			"egress_49696.yaml":                   &bintree{networkingNetworkpolicyEgress_49696Yaml, map[string]*bintree{}},
			"generic-networkpolicy-template.yaml": &bintree{networkingNetworkpolicyGenericNetworkpolicyTemplateYaml, map[string]*bintree{}},
			"ingress-allow-all.yaml":              &bintree{networkingNetworkpolicyIngressAllowAllYaml, map[string]*bintree{}},
			"ingress_49696.yaml":                  &bintree{networkingNetworkpolicyIngress_49696Yaml, map[string]*bintree{}},
			"ipblock": &bintree{nil, map[string]*bintree{
				"ipBlock-egress-dual-CIDRs-template.yaml":             &bintree{networkingNetworkpolicyIpblockIpblockEgressDualCidrsTemplateYaml, map[string]*bintree{}},
				"ipBlock-egress-dual-multiple-CIDRs-template.yaml":    &bintree{networkingNetworkpolicyIpblockIpblockEgressDualMultipleCidrsTemplateYaml, map[string]*bintree{}},
				"ipBlock-egress-except-dual-CIDRs-template.yaml":      &bintree{networkingNetworkpolicyIpblockIpblockEgressExceptDualCidrsTemplateYaml, map[string]*bintree{}},
				"ipBlock-egress-except-single-CIDR-template.yaml":     &bintree{networkingNetworkpolicyIpblockIpblockEgressExceptSingleCidrTemplateYaml, map[string]*bintree{}},
				"ipBlock-egress-single-CIDR-template.yaml":            &bintree{networkingNetworkpolicyIpblockIpblockEgressSingleCidrTemplateYaml, map[string]*bintree{}},
				"ipBlock-egress-single-multiple-CIDRs-template.yaml":  &bintree{networkingNetworkpolicyIpblockIpblockEgressSingleMultipleCidrsTemplateYaml, map[string]*bintree{}},
				"ipBlock-ingress-dual-CIDRs-template.yaml":            &bintree{networkingNetworkpolicyIpblockIpblockIngressDualCidrsTemplateYaml, map[string]*bintree{}},
				"ipBlock-ingress-dual-multiple-CIDRs-template.yaml":   &bintree{networkingNetworkpolicyIpblockIpblockIngressDualMultipleCidrsTemplateYaml, map[string]*bintree{}},
				"ipBlock-ingress-single-CIDR-template.yaml":           &bintree{networkingNetworkpolicyIpblockIpblockIngressSingleCidrTemplateYaml, map[string]*bintree{}},
				"ipBlock-ingress-single-multiple-CIDRs-template.yaml": &bintree{networkingNetworkpolicyIpblockIpblockIngressSingleMultipleCidrsTemplateYaml, map[string]*bintree{}},
			}},
			"netpol-30920-75540.yaml":             &bintree{networkingNetworkpolicyNetpol3092075540Yaml, map[string]*bintree{}},
			"vap-npprotection-blockdeletion.yaml": &bintree{networkingNetworkpolicyVapNpprotectionBlockdeletionYaml, map[string]*bintree{}},
		}},
		"ping-for-pod-specific-node-template.yaml": &bintree{networkingPingForPodSpecificNodeTemplateYaml, map[string]*bintree{}},
		"ping-for-pod-template.yaml":               &bintree{networkingPingForPodTemplateYaml, map[string]*bintree{}},
		"service-generic-template.yaml":            &bintree{networkingServiceGenericTemplateYaml, map[string]*bintree{}},
		"statefulset-hello.yaml":                   &bintree{networkingStatefulsetHelloYaml, map[string]*bintree{}},
		"testpod.yaml":                             &bintree{networkingTestpodYaml, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

var fixtureDir string

func FixturePath(elem ...string) string {
	if fixtureDir == "" {
		dir, err := os.MkdirTemp("", "otp-testdata-")
		if err != nil {
			panic(fmt.Sprintf("failed to create temp dir for testdata: %v", err))
		}
		if err := RestoreAssets(dir, "networking"); err != nil {
			panic(fmt.Sprintf("failed to restore testdata assets: %v", err))
		}
		fixtureDir = dir
	}
	return filepath.Join(append([]string{fixtureDir}, elem...)...)
}
