//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Bandwidth) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.networkqos.v1alpha1.Bandwidth"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Classifier) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.networkqos.v1alpha1.Classifier"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Destination) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.networkqos.v1alpha1.Destination"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkQoS) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.networkqos.v1alpha1.NetworkQoS"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkQoSList) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.networkqos.v1alpha1.NetworkQoSList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Port) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.networkqos.v1alpha1.Port"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Rule) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.networkqos.v1alpha1.Rule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Spec) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.networkqos.v1alpha1.Spec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Status) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.networkqos.v1alpha1.Status"
}
