// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/networkqos/v1alpha1"
	internal "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/networkqos/v1alpha1/apis/applyconfiguration/internal"
	networkqosv1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/networkqos/v1alpha1/apis/applyconfiguration/networkqos/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=k8s.ovn.org, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("Bandwidth"):
		return &networkqosv1alpha1.BandwidthApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Classifier"):
		return &networkqosv1alpha1.ClassifierApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Destination"):
		return &networkqosv1alpha1.DestinationApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkQoS"):
		return &networkqosv1alpha1.NetworkQoSApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Port"):
		return &networkqosv1alpha1.PortApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Rule"):
		return &networkqosv1alpha1.RuleApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Spec"):
		return &networkqosv1alpha1.SpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Status"):
		return &networkqosv1alpha1.StatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
