//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by openapi-gen. DO NOT EDIT.

package v1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressFirewall) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.egressfirewall.v1.EgressFirewall"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressFirewallDestination) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.egressfirewall.v1.EgressFirewallDestination"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressFirewallList) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.egressfirewall.v1.EgressFirewallList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressFirewallPort) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.egressfirewall.v1.EgressFirewallPort"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressFirewallRule) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.egressfirewall.v1.EgressFirewallRule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressFirewallSpec) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.egressfirewall.v1.EgressFirewallSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressFirewallStatus) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.egressfirewall.v1.EgressFirewallStatus"
}
