// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// VTEPStatusApplyConfiguration represents a declarative configuration of the VTEPStatus type for use
// with apply.
//
// VTEPStatus contains the observed state of the VTEP.
type VTEPStatusApplyConfiguration struct {
	// Conditions slice of condition objects indicating details about VTEP status.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// VTEPStatusApplyConfiguration constructs a declarative configuration of the VTEPStatus type for use with
// apply.
func VTEPStatus() *VTEPStatusApplyConfiguration {
	return &VTEPStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *VTEPStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *VTEPStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
