// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/adminpolicybasedroute/v1"
	adminpolicybasedroutev1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/adminpolicybasedroute/v1/apis/applyconfiguration/adminpolicybasedroute/v1"
	typedadminpolicybasedroutev1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/adminpolicybasedroute/v1/apis/clientset/versioned/typed/adminpolicybasedroute/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeAdminPolicyBasedExternalRoutes implements AdminPolicyBasedExternalRouteInterface
type fakeAdminPolicyBasedExternalRoutes struct {
	*gentype.FakeClientWithListAndApply[*v1.AdminPolicyBasedExternalRoute, *v1.AdminPolicyBasedExternalRouteList, *adminpolicybasedroutev1.AdminPolicyBasedExternalRouteApplyConfiguration]
	Fake *FakeK8sV1
}

func newFakeAdminPolicyBasedExternalRoutes(fake *FakeK8sV1) typedadminpolicybasedroutev1.AdminPolicyBasedExternalRouteInterface {
	return &fakeAdminPolicyBasedExternalRoutes{
		gentype.NewFakeClientWithListAndApply[*v1.AdminPolicyBasedExternalRoute, *v1.AdminPolicyBasedExternalRouteList, *adminpolicybasedroutev1.AdminPolicyBasedExternalRouteApplyConfiguration](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("adminpolicybasedexternalroutes"),
			v1.SchemeGroupVersion.WithKind("AdminPolicyBasedExternalRoute"),
			func() *v1.AdminPolicyBasedExternalRoute { return &v1.AdminPolicyBasedExternalRoute{} },
			func() *v1.AdminPolicyBasedExternalRouteList { return &v1.AdminPolicyBasedExternalRouteList{} },
			func(dst, src *v1.AdminPolicyBasedExternalRouteList) { dst.ListMeta = src.ListMeta },
			func(list *v1.AdminPolicyBasedExternalRouteList) []*v1.AdminPolicyBasedExternalRoute {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.AdminPolicyBasedExternalRouteList, items []*v1.AdminPolicyBasedExternalRoute) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
