// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	egressfirewallv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressfirewall/v1"
)

// EgressFirewallRuleApplyConfiguration represents a declarative configuration of the EgressFirewallRule type for use
// with apply.
//
// EgressFirewallRule is a single egressfirewall rule object
type EgressFirewallRuleApplyConfiguration struct {
	// type marks this as an "Allow" or "Deny" rule
	Type *egressfirewallv1.EgressFirewallRuleType `json:"type,omitempty"`
	// ports specify what ports and protocols the rule applies to
	Ports []EgressFirewallPortApplyConfiguration `json:"ports,omitempty"`
	// to is the target that traffic is allowed/denied to
	To *EgressFirewallDestinationApplyConfiguration `json:"to,omitempty"`
}

// EgressFirewallRuleApplyConfiguration constructs a declarative configuration of the EgressFirewallRule type for use with
// apply.
func EgressFirewallRule() *EgressFirewallRuleApplyConfiguration {
	return &EgressFirewallRuleApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *EgressFirewallRuleApplyConfiguration) WithType(value egressfirewallv1.EgressFirewallRuleType) *EgressFirewallRuleApplyConfiguration {
	b.Type = &value
	return b
}

// WithPorts adds the given value to the Ports field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Ports field.
func (b *EgressFirewallRuleApplyConfiguration) WithPorts(values ...*EgressFirewallPortApplyConfiguration) *EgressFirewallRuleApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPorts")
		}
		b.Ports = append(b.Ports, *values[i])
	}
	return b
}

// WithTo sets the To field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the To field is set to the value of the last call.
func (b *EgressFirewallRuleApplyConfiguration) WithTo(value *EgressFirewallDestinationApplyConfiguration) *EgressFirewallRuleApplyConfiguration {
	b.To = value
	return b
}
