// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// EgressFirewallSpecApplyConfiguration represents a declarative configuration of the EgressFirewallSpec type for use
// with apply.
//
// EgressFirewallSpec is a desired state description of EgressFirewall.
type EgressFirewallSpecApplyConfiguration struct {
	// a collection of egress firewall rule objects
	Egress []EgressFirewallRuleApplyConfiguration `json:"egress,omitempty"`
}

// EgressFirewallSpecApplyConfiguration constructs a declarative configuration of the EgressFirewallSpec type for use with
// apply.
func EgressFirewallSpec() *EgressFirewallSpecApplyConfiguration {
	return &EgressFirewallSpecApplyConfiguration{}
}

// WithEgress adds the given value to the Egress field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Egress field.
func (b *EgressFirewallSpecApplyConfiguration) WithEgress(values ...*EgressFirewallRuleApplyConfiguration) *EgressFirewallSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEgress")
		}
		b.Egress = append(b.Egress, *values[i])
	}
	return b
}
