// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

import "github.com/ovn-kubernetes/libovsdb/model"

const LearnedRouteTable = "Learned_Route"

// LearnedRoute defines an object in Learned_Route table
type LearnedRoute struct {
	UUID        string            `ovsdb:"_uuid"`
	Datapath    string            `ovsdb:"datapath"`
	ExternalIDs map[string]string `ovsdb:"external_ids"`
	IPPrefix    string            `ovsdb:"ip_prefix"`
	LogicalPort string            `ovsdb:"logical_port"`
	Nexthop     string            `ovsdb:"nexthop"`
}

func (a *LearnedRoute) GetUUID() string {
	return a.UUID
}

func (a *LearnedRoute) GetDatapath() string {
	return a.Datapath
}

func (a *LearnedRoute) GetExternalIDs() map[string]string {
	return a.ExternalIDs
}

func copyLearnedRouteExternalIDs(a map[string]string) map[string]string {
	if a == nil {
		return nil
	}
	b := make(map[string]string, len(a))
	for k, v := range a {
		b[k] = v
	}
	return b
}

func equalLearnedRouteExternalIDs(a, b map[string]string) bool {
	if (a == nil) != (b == nil) {
		return false
	}
	if len(a) != len(b) {
		return false
	}
	for k, v := range a {
		if w, ok := b[k]; !ok || v != w {
			return false
		}
	}
	return true
}

func (a *LearnedRoute) GetIPPrefix() string {
	return a.IPPrefix
}

func (a *LearnedRoute) GetLogicalPort() string {
	return a.LogicalPort
}

func (a *LearnedRoute) GetNexthop() string {
	return a.Nexthop
}

func (a *LearnedRoute) DeepCopyInto(b *LearnedRoute) {
	*b = *a
	b.ExternalIDs = copyLearnedRouteExternalIDs(a.ExternalIDs)
}

func (a *LearnedRoute) DeepCopy() *LearnedRoute {
	b := new(LearnedRoute)
	a.DeepCopyInto(b)
	return b
}

func (a *LearnedRoute) CloneModelInto(b model.Model) {
	c := b.(*LearnedRoute)
	a.DeepCopyInto(c)
}

func (a *LearnedRoute) CloneModel() model.Model {
	return a.DeepCopy()
}

func (a *LearnedRoute) Equals(b *LearnedRoute) bool {
	return a.UUID == b.UUID &&
		a.Datapath == b.Datapath &&
		equalLearnedRouteExternalIDs(a.ExternalIDs, b.ExternalIDs) &&
		a.IPPrefix == b.IPPrefix &&
		a.LogicalPort == b.LogicalPort &&
		a.Nexthop == b.Nexthop
}

func (a *LearnedRoute) EqualsModel(b model.Model) bool {
	c := b.(*LearnedRoute)
	return a.Equals(c)
}

var _ model.CloneableModel = &LearnedRoute{}
var _ model.ComparableModel = &LearnedRoute{}
