//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by openapi-gen. DO NOT EDIT.

package v1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AccessVLANConfig) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.userdefinednetwork.v1.AccessVLANConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterUserDefinedNetwork) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.userdefinednetwork.v1.ClusterUserDefinedNetwork"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterUserDefinedNetworkList) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.userdefinednetwork.v1.ClusterUserDefinedNetworkList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterUserDefinedNetworkSpec) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.userdefinednetwork.v1.ClusterUserDefinedNetworkSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterUserDefinedNetworkStatus) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.userdefinednetwork.v1.ClusterUserDefinedNetworkStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EVPNConfig) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.userdefinednetwork.v1.EVPNConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAMConfig) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.userdefinednetwork.v1.IPAMConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Layer2Config) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.userdefinednetwork.v1.Layer2Config"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Layer3Config) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.userdefinednetwork.v1.Layer3Config"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Layer3Subnet) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.userdefinednetwork.v1.Layer3Subnet"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LocalnetConfig) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.userdefinednetwork.v1.LocalnetConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkSpec) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.userdefinednetwork.v1.NetworkSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NoOverlayConfig) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.userdefinednetwork.v1.NoOverlayConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UserDefinedNetwork) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.userdefinednetwork.v1.UserDefinedNetwork"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UserDefinedNetworkList) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.userdefinednetwork.v1.UserDefinedNetworkList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UserDefinedNetworkSpec) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.userdefinednetwork.v1.UserDefinedNetworkSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UserDefinedNetworkStatus) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.userdefinednetwork.v1.UserDefinedNetworkStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VLANConfig) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.userdefinednetwork.v1.VLANConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VRFConfig) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.userdefinednetwork.v1.VRFConfig"
}
