authors:
  trozet:
    name: Tim Rozet
    description: Software Engineer at NVIDIA.
    avatar: https://github.com/trozet.png
  npinaeva:
    name: Nadia Pinaeva
    description: Software Engineer at Red Hat.
    avatar: https://github.com/npinaeva.png
