authors:
  trozet:
    name: Tim Rozet
    description: Software Engineer at NVIDIA.
    avatar: https://github.com/trozet.png
  npinaeva:
    name: Nadia Pinaeva
    description: Software Engineer at NVIDIA.
    avatar: https://github.com/npinaeva.png
  Soli0222:
    name: Taichi Shimotori
    description: Site Reliability Engineer at Internet Initiative Japan Inc. (IIJ).
    avatar: https://raw.githubusercontent.com/cncf/people/main/images/taichi-shimotori.jpg
  kyrtapz:
    name: Patryk Diak
    description: Software Engineer at Red Hat.
    avatar: https://github.com/kyrtapz.png
  fangyuchen:
    name: Fang YuChen
    description: Cloud Platform Architect at SAIC Motor.
    avatar: https://github.com/fangyuchen86.png
