// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressip/v1"
	egressipv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressip/v1/apis/applyconfiguration/egressip/v1"
	typedegressipv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressip/v1/apis/clientset/versioned/typed/egressip/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeEgressIPs implements EgressIPInterface
type fakeEgressIPs struct {
	*gentype.FakeClientWithListAndApply[*v1.EgressIP, *v1.EgressIPList, *egressipv1.EgressIPApplyConfiguration]
	Fake *FakeK8sV1
}

func newFakeEgressIPs(fake *FakeK8sV1) typedegressipv1.EgressIPInterface {
	return &fakeEgressIPs{
		gentype.NewFakeClientWithListAndApply[*v1.EgressIP, *v1.EgressIPList, *egressipv1.EgressIPApplyConfiguration](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("egressips"),
			v1.SchemeGroupVersion.WithKind("EgressIP"),
			func() *v1.EgressIP { return &v1.EgressIP{} },
			func() *v1.EgressIPList { return &v1.EgressIPList{} },
			func(dst, src *v1.EgressIPList) { dst.ListMeta = src.ListMeta },
			func(list *v1.EgressIPList) []*v1.EgressIP { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.EgressIPList, items []*v1.EgressIP) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
