//go:build linux
// +build linux

package cni

import (
	"fmt"

	configv1 "github.com/openshift/api/config/v1"
	"github.com/ovn-org/ovn-kubernetes/go-controller/pkg/config"
)

const baseRestoreDataFmt string = `# Generated by ovnkube-node
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
# Block Machine Config Service
-A FORWARD -p tcp -m tcp --dport 22623 --tcp-flags FIN,SYN,RST,ACK SYN -j REJECT --reject-with %s
-A FORWARD -p tcp -m tcp --dport 22624 --tcp-flags FIN,SYN,RST,ACK SYN -j REJECT --reject-with %s
-A OUTPUT -p tcp -m tcp --dport 22623 --tcp-flags FIN,SYN,RST,ACK SYN -j REJECT --reject-with %s
-A OUTPUT -p tcp -m tcp --dport 22624 --tcp-flags FIN,SYN,RST,ACK SYN -j REJECT --reject-with %s
%s
COMMIT
`

func generateRestoreData(isIPv4 bool) string {
	icmpReject := "icmp6-port-unreachable"

	var appendData string
	if isIPv4 {
		icmpReject = "icmp-port-unreachable"
		metadataServiceIP := "169.254.169.254"
		if config.Kubernetes.PlatformType == string(configv1.AlibabaCloudPlatformType) {
			metadataServiceIP = "100.100.100.200"
		}

		appendData = fmt.Sprintf(`# Block cloud provider metadata IP except DNS
-A FORWARD -d %s -p tcp -m tcp ! --dport 53 -j REJECT --reject-with icmp-port-unreachable
-A FORWARD -d %s -p udp -m udp ! --dport 53 -j REJECT --reject-with icmp-port-unreachable
-A OUTPUT -d %s -p tcp -m tcp ! --dport 53 -j REJECT --reject-with icmp-port-unreachable
-A OUTPUT -d %s -p udp -m udp ! --dport 53 -j REJECT --reject-with icmp-port-unreachable
`, metadataServiceIP, metadataServiceIP, metadataServiceIP, metadataServiceIP)
	}

	return fmt.Sprintf(baseRestoreDataFmt, icmpReject, icmpReject, icmpReject, icmpReject, appendData)
}
