// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	uplinkv1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/uplink/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// UplinkLister helps list Uplinks.
// All objects returned here must be treated as read-only.
type UplinkLister interface {
	// List lists all Uplinks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*uplinkv1alpha1.Uplink, err error)
	// Get retrieves the Uplink from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*uplinkv1alpha1.Uplink, error)
	UplinkListerExpansion
}

// uplinkLister implements the UplinkLister interface.
type uplinkLister struct {
	listers.ResourceIndexer[*uplinkv1alpha1.Uplink]
}

// NewUplinkLister returns a new UplinkLister.
func NewUplinkLister(indexer cache.Indexer) UplinkLister {
	return &uplinkLister{listers.New[*uplinkv1alpha1.Uplink](indexer, uplinkv1alpha1.Resource("uplink"))}
}
