// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/uplink/v1alpha1"
	internal "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/uplink/v1alpha1/apis/applyconfiguration/internal"
	uplinkv1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/uplink/v1alpha1/apis/applyconfiguration/uplink/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=k8s.ovn.org, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("OVSBridgeStatus"):
		return &uplinkv1alpha1.OVSBridgeStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Uplink"):
		return &uplinkv1alpha1.UplinkApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("UplinkNodeConfig"):
		return &uplinkv1alpha1.UplinkNodeConfigApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("UplinkSpec"):
		return &uplinkv1alpha1.UplinkSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("UplinkState"):
		return &uplinkv1alpha1.UplinkStateApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("UplinkStateSpec"):
		return &uplinkv1alpha1.UplinkStateSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("UplinkStateStatus"):
		return &uplinkv1alpha1.UplinkStateStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("UplinkStatus"):
		return &uplinkv1alpha1.UplinkStatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
