//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by deepcopy-gen. DO NOT EDIT.

package types

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterUserDefinedNetworkSelector) DeepCopyInto(out *ClusterUserDefinedNetworkSelector) {
	*out = *in
	in.NetworkSelector.DeepCopyInto(&out.NetworkSelector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterUserDefinedNetworkSelector.
func (in *ClusterUserDefinedNetworkSelector) DeepCopy() *ClusterUserDefinedNetworkSelector {
	if in == nil {
		return nil
	}
	out := new(ClusterUserDefinedNetworkSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkAttachmentDefinitionSelector) DeepCopyInto(out *NetworkAttachmentDefinitionSelector) {
	*out = *in
	in.NamespaceSelector.DeepCopyInto(&out.NamespaceSelector)
	in.NetworkSelector.DeepCopyInto(&out.NetworkSelector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkAttachmentDefinitionSelector.
func (in *NetworkAttachmentDefinitionSelector) DeepCopy() *NetworkAttachmentDefinitionSelector {
	if in == nil {
		return nil
	}
	out := new(NetworkAttachmentDefinitionSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSelector) DeepCopyInto(out *NetworkSelector) {
	*out = *in
	if in.ClusterUserDefinedNetworkSelector != nil {
		in, out := &in.ClusterUserDefinedNetworkSelector, &out.ClusterUserDefinedNetworkSelector
		*out = new(ClusterUserDefinedNetworkSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PrimaryUserDefinedNetworkSelector != nil {
		in, out := &in.PrimaryUserDefinedNetworkSelector, &out.PrimaryUserDefinedNetworkSelector
		*out = new(PrimaryUserDefinedNetworkSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SecondaryUserDefinedNetworkSelector != nil {
		in, out := &in.SecondaryUserDefinedNetworkSelector, &out.SecondaryUserDefinedNetworkSelector
		*out = new(SecondaryUserDefinedNetworkSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkAttachmentDefinitionSelector != nil {
		in, out := &in.NetworkAttachmentDefinitionSelector, &out.NetworkAttachmentDefinitionSelector
		*out = new(NetworkAttachmentDefinitionSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSelector.
func (in *NetworkSelector) DeepCopy() *NetworkSelector {
	if in == nil {
		return nil
	}
	out := new(NetworkSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in NetworkSelectors) DeepCopyInto(out *NetworkSelectors) {
	{
		in := &in
		*out = make(NetworkSelectors, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSelectors.
func (in NetworkSelectors) DeepCopy() NetworkSelectors {
	if in == nil {
		return nil
	}
	out := new(NetworkSelectors)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrimaryUserDefinedNetworkSelector) DeepCopyInto(out *PrimaryUserDefinedNetworkSelector) {
	*out = *in
	in.NamespaceSelector.DeepCopyInto(&out.NamespaceSelector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrimaryUserDefinedNetworkSelector.
func (in *PrimaryUserDefinedNetworkSelector) DeepCopy() *PrimaryUserDefinedNetworkSelector {
	if in == nil {
		return nil
	}
	out := new(PrimaryUserDefinedNetworkSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecondaryUserDefinedNetworkSelector) DeepCopyInto(out *SecondaryUserDefinedNetworkSelector) {
	*out = *in
	in.NamespaceSelector.DeepCopyInto(&out.NamespaceSelector)
	in.NetworkSelector.DeepCopyInto(&out.NetworkSelector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecondaryUserDefinedNetworkSelector.
func (in *SecondaryUserDefinedNetworkSelector) DeepCopy() *SecondaryUserDefinedNetworkSelector {
	if in == nil {
		return nil
	}
	out := new(SecondaryUserDefinedNetworkSelector)
	in.DeepCopyInto(out)
	return out
}
