//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by openapi-gen. DO NOT EDIT.

package types

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterUserDefinedNetworkSelector) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.types.ClusterUserDefinedNetworkSelector"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkAttachmentDefinitionSelector) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.types.NetworkAttachmentDefinitionSelector"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkSelector) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.types.NetworkSelector"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PrimaryUserDefinedNetworkSelector) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.types.PrimaryUserDefinedNetworkSelector"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SecondaryUserDefinedNetworkSelector) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.types.SecondaryUserDefinedNetworkSelector"
}
