nbLogLevel: "-vconsole:info -vfile:info"
sbLogLevel: "-vconsole:info -vfile:info"
northdLogLevel: "-vconsole:info -vfile:info"
ovnkubeNodeLogLevel: 4
ovnControllerLogLevel: "-vconsole:info"
logFileMaxSize: 100
logFileMaxBackups: 5
logFileMaxAge: 5
libovsdbClientLogFile: ""

# To utilize hardware offloading for management ports, a netdevice or a deviceplugin resource name that
# specifies a pool of devices can be specified.
# mgmtPortVFResourceName will override nodeMgmtPortNetdev if both are specified

# The net device to be used for management ports
nodeMgmtPortNetdev: ""

# The device plugin resource name that identifies the allocated interfaces to be used for management ports
# This field must be set when using hardware offloading for primary UDNs.
mgmtPortVFResourceName: ""

# If using hardware offloading for primary UDNs,the number of VFs required to handle management ports,
# which depends on the number of primary UDNs required must also be specified.
mgmtPortVFsCount: 1
