// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressqos/v1"
	egressqosv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressqos/v1/apis/applyconfiguration/egressqos/v1"
	typedegressqosv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressqos/v1/apis/clientset/versioned/typed/egressqos/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeEgressQoSes implements EgressQoSInterface
type fakeEgressQoSes struct {
	*gentype.FakeClientWithListAndApply[*v1.EgressQoS, *v1.EgressQoSList, *egressqosv1.EgressQoSApplyConfiguration]
	Fake *FakeK8sV1
}

func newFakeEgressQoSes(fake *FakeK8sV1, namespace string) typedegressqosv1.EgressQoSInterface {
	return &fakeEgressQoSes{
		gentype.NewFakeClientWithListAndApply[*v1.EgressQoS, *v1.EgressQoSList, *egressqosv1.EgressQoSApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("egressqoses"),
			v1.SchemeGroupVersion.WithKind("EgressQoS"),
			func() *v1.EgressQoS { return &v1.EgressQoS{} },
			func() *v1.EgressQoSList { return &v1.EgressQoSList{} },
			func(dst, src *v1.EgressQoSList) { dst.ListMeta = src.ListMeta },
			func(list *v1.EgressQoSList) []*v1.EgressQoS { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.EgressQoSList, items []*v1.EgressQoS) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
