---
kind: Namespace
apiVersion: v1
metadata:
  name: {{.JobName}}-{{sub .Replica 1}}
  labels:
    k8s.ovn.org/primary-user-defined-network: ""
    kube-burner.io/cudn-group: group-{{ div (sub .Replica 1) 5 }}
