// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AccessVLANConfigApplyConfiguration represents a declarative configuration of the AccessVLANConfig type for use
// with apply.
//
// AccessVLANConfig describes an access VLAN configuration.
type AccessVLANConfigApplyConfiguration struct {
	// id is the VLAN ID (VID) to be set for the network.
	// id should be higher than 0 and lower than 4095.
	ID *int32 `json:"id,omitempty"`
}

// AccessVLANConfigApplyConfiguration constructs a declarative configuration of the AccessVLANConfig type for use with
// apply.
func AccessVLANConfig() *AccessVLANConfigApplyConfiguration {
	return &AccessVLANConfigApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *AccessVLANConfigApplyConfiguration) WithID(value int32) *AccessVLANConfigApplyConfiguration {
	b.ID = &value
	return b
}
