// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterUserDefinedNetworkSpecApplyConfiguration represents a declarative configuration of the ClusterUserDefinedNetworkSpec type for use
// with apply.
//
// ClusterUserDefinedNetworkSpec defines the desired state of ClusterUserDefinedNetwork.
type ClusterUserDefinedNetworkSpecApplyConfiguration struct {
	// NamespaceSelector Label selector for which namespace network should be available for.
	NamespaceSelector *metav1.LabelSelectorApplyConfiguration `json:"namespaceSelector,omitempty"`
	// Network is the user-defined-network spec
	Network *NetworkSpecApplyConfiguration `json:"network,omitempty"`
}

// ClusterUserDefinedNetworkSpecApplyConfiguration constructs a declarative configuration of the ClusterUserDefinedNetworkSpec type for use with
// apply.
func ClusterUserDefinedNetworkSpec() *ClusterUserDefinedNetworkSpecApplyConfiguration {
	return &ClusterUserDefinedNetworkSpecApplyConfiguration{}
}

// WithNamespaceSelector sets the NamespaceSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespaceSelector field is set to the value of the last call.
func (b *ClusterUserDefinedNetworkSpecApplyConfiguration) WithNamespaceSelector(value *metav1.LabelSelectorApplyConfiguration) *ClusterUserDefinedNetworkSpecApplyConfiguration {
	b.NamespaceSelector = value
	return b
}

// WithNetwork sets the Network field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Network field is set to the value of the last call.
func (b *ClusterUserDefinedNetworkSpecApplyConfiguration) WithNetwork(value *NetworkSpecApplyConfiguration) *ClusterUserDefinedNetworkSpecApplyConfiguration {
	b.Network = value
	return b
}
