// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterUserDefinedNetworkStatusApplyConfiguration represents a declarative configuration of the ClusterUserDefinedNetworkStatus type for use
// with apply.
//
// ClusterUserDefinedNetworkStatus contains the observed status of the ClusterUserDefinedNetwork.
type ClusterUserDefinedNetworkStatusApplyConfiguration struct {
	// Conditions slice of condition objects indicating details about ClusterUserDefineNetwork status.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ClusterUserDefinedNetworkStatusApplyConfiguration constructs a declarative configuration of the ClusterUserDefinedNetworkStatus type for use with
// apply.
func ClusterUserDefinedNetworkStatus() *ClusterUserDefinedNetworkStatusApplyConfiguration {
	return &ClusterUserDefinedNetworkStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ClusterUserDefinedNetworkStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *ClusterUserDefinedNetworkStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
