/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	userdefinednetworkv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/userdefinednetwork/v1"
)

// Layer2ConfigApplyConfiguration represents a declarative configuration of the Layer2Config type for use
// with apply.
type Layer2ConfigApplyConfiguration struct {
	// Role describes the network role in the pod.
	//
	// Allowed value is "Secondary".
	// Secondary network is only assigned to pods that use `k8s.v1.cni.cncf.io/networks` annotation to select given network.
	Role *userdefinednetworkv1.NetworkRole `json:"role,omitempty"`
	// MTU is the maximum transmission unit for a network.
	// MTU is optional, if not provided, the globally configured value in OVN-Kubernetes (defaults to 1400) is used for the network.
	MTU *int32 `json:"mtu,omitempty"`
	// Subnets are used for the pod network across the cluster.
	// Dual-stack clusters may set 2 subnets (one for each IP family), otherwise only 1 subnet is allowed.
	//
	// The format should match standard CIDR notation (for example, "10.128.0.0/16").
	// This field must be omitted if `ipam.mode` is `Disabled`.
	Subnets *userdefinednetworkv1.DualStackCIDRs `json:"subnets,omitempty"`
	// reservedSubnets specifies a list of CIDRs reserved for static IP assignment, excluded from automatic allocation.
	// reservedSubnets is optional. When omitted, all IP addresses in `subnets` are available for automatic assignment.
	// IPs from these ranges can still be requested through static IP assignment.
	// Each item should be in range of the specified CIDR(s) in `subnets`.
	// The maximum number of entries allowed is 25.
	// The format should match standard CIDR notation (for example, "10.128.0.0/16").
	// This field must be omitted if `subnets` is unset or `ipam.mode` is `Disabled`.
	ReservedSubnets []userdefinednetworkv1.CIDR `json:"reservedSubnets,omitempty"`
	// infrastructureSubnets specifies a list of internal CIDR ranges that OVN-Kubernetes will reserve for internal network infrastructure.
	// Any IP addresses within these ranges cannot be assigned to workloads.
	// When omitted, OVN-Kubernetes will automatically allocate IP addresses from `subnets` for its infrastructure needs.
	// When there are not enough available IPs in the provided infrastructureSubnets, OVN-Kubernetes will automatically allocate IP addresses from subnets for its infrastructure needs.
	// When `reservedSubnets` is also specified the CIDRs cannot overlap.
	// When `defaultGatewayIPs` is also specified, the default gateway IPs must belong to one of the infrastructure subnet CIDRs.
	// Each item should be in range of the specified CIDR(s) in `subnets`.
	// The maximum number of entries allowed is 4.
	// The format should match standard CIDR notation (for example, "10.128.0.0/16").
	// This field must be omitted if `subnets` is unset or `ipam.mode` is `Disabled`.
	InfrastructureSubnets []userdefinednetworkv1.CIDR `json:"infrastructureSubnets,omitempty"`
	// defaultGatewayIPs specifies the default gateway IP used in the internal OVN topology.
	//
	// Dual-stack clusters may set 2 IPs (one for each IP family), otherwise only 1 IP is allowed.
	// This field is only allowed for "Primary" network.
	// It is not recommended to set this field without explicit need and understanding of the OVN network topology.
	// When omitted, an IP from the subnets field is used.
	DefaultGatewayIPs *userdefinednetworkv1.DualStackIPs `json:"defaultGatewayIPs,omitempty"`
	// JoinSubnets are used inside the OVN network topology.
	//
	// Dual-stack clusters may set 2 subnets (one for each IP family), otherwise only 1 subnet is allowed.
	// This field is only allowed for "Primary" network.
	// It is not recommended to set this field without explicit need and understanding of the OVN network topology.
	// When omitted, the platform will choose a reasonable default which is subject to change over time.
	JoinSubnets *userdefinednetworkv1.DualStackCIDRs `json:"joinSubnets,omitempty"`
	// IPAM section contains IPAM-related configuration for the network.
	IPAM *IPAMConfigApplyConfiguration `json:"ipam,omitempty"`
}

// Layer2ConfigApplyConfiguration constructs a declarative configuration of the Layer2Config type for use with
// apply.
func Layer2Config() *Layer2ConfigApplyConfiguration {
	return &Layer2ConfigApplyConfiguration{}
}

// WithRole sets the Role field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Role field is set to the value of the last call.
func (b *Layer2ConfigApplyConfiguration) WithRole(value userdefinednetworkv1.NetworkRole) *Layer2ConfigApplyConfiguration {
	b.Role = &value
	return b
}

// WithMTU sets the MTU field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MTU field is set to the value of the last call.
func (b *Layer2ConfigApplyConfiguration) WithMTU(value int32) *Layer2ConfigApplyConfiguration {
	b.MTU = &value
	return b
}

// WithSubnets sets the Subnets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Subnets field is set to the value of the last call.
func (b *Layer2ConfigApplyConfiguration) WithSubnets(value userdefinednetworkv1.DualStackCIDRs) *Layer2ConfigApplyConfiguration {
	b.Subnets = &value
	return b
}

// WithReservedSubnets adds the given value to the ReservedSubnets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ReservedSubnets field.
func (b *Layer2ConfigApplyConfiguration) WithReservedSubnets(values ...userdefinednetworkv1.CIDR) *Layer2ConfigApplyConfiguration {
	for i := range values {
		b.ReservedSubnets = append(b.ReservedSubnets, values[i])
	}
	return b
}

// WithInfrastructureSubnets adds the given value to the InfrastructureSubnets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the InfrastructureSubnets field.
func (b *Layer2ConfigApplyConfiguration) WithInfrastructureSubnets(values ...userdefinednetworkv1.CIDR) *Layer2ConfigApplyConfiguration {
	for i := range values {
		b.InfrastructureSubnets = append(b.InfrastructureSubnets, values[i])
	}
	return b
}

// WithDefaultGatewayIPs sets the DefaultGatewayIPs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultGatewayIPs field is set to the value of the last call.
func (b *Layer2ConfigApplyConfiguration) WithDefaultGatewayIPs(value userdefinednetworkv1.DualStackIPs) *Layer2ConfigApplyConfiguration {
	b.DefaultGatewayIPs = &value
	return b
}

// WithJoinSubnets sets the JoinSubnets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JoinSubnets field is set to the value of the last call.
func (b *Layer2ConfigApplyConfiguration) WithJoinSubnets(value userdefinednetworkv1.DualStackCIDRs) *Layer2ConfigApplyConfiguration {
	b.JoinSubnets = &value
	return b
}

// WithIPAM sets the IPAM field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPAM field is set to the value of the last call.
func (b *Layer2ConfigApplyConfiguration) WithIPAM(value *IPAMConfigApplyConfiguration) *Layer2ConfigApplyConfiguration {
	b.IPAM = value
	return b
}
