// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	userdefinednetworkv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/userdefinednetwork/v1"
)

// MACSecurityConfigApplyConfiguration represents a declarative configuration of the MACSecurityConfig type for use
// with apply.
//
// MACSecurityConfig configures MAC spoof protection behavior.
type MACSecurityConfigApplyConfiguration struct {
	// mode controls the MAC spoof protection enforcement posture.
	// `Enabled` (default) restricts traffic to assigned addresses.
	// `Disabled` removes all MAC spoof protection restrictions and enables unknown MAC address
	// handling for nested virtualization and NFV use cases.
	// Only `Disabled` requires ipam.mode to be Disabled.
	Mode *userdefinednetworkv1.MACSecurityMode `json:"mode,omitempty"`
}

// MACSecurityConfigApplyConfiguration constructs a declarative configuration of the MACSecurityConfig type for use with
// apply.
func MACSecurityConfig() *MACSecurityConfigApplyConfiguration {
	return &MACSecurityConfigApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *MACSecurityConfigApplyConfiguration) WithMode(value userdefinednetworkv1.MACSecurityMode) *MACSecurityConfigApplyConfiguration {
	b.Mode = &value
	return b
}
