/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	userdefinednetworkv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/userdefinednetwork/v1"
)

// NetworkSpecApplyConfiguration represents a declarative configuration of the NetworkSpec type for use
// with apply.
//
// NetworkSpec defines the desired state of UserDefinedNetworkSpec.
type NetworkSpecApplyConfiguration struct {
	// Topology describes network configuration.
	//
	// Allowed values are "Layer3", "Layer2" and "Localnet".
	// Layer3 topology creates a layer 2 segment per node, each with a different subnet. Layer 3 routing is used to interconnect node subnets.
	// Layer2 topology creates one logical switch shared by all nodes.
	// Localnet topology is based on layer 2 topology, but also allows connecting to an existent (configured) physical network to provide north-south traffic to the workloads.
	Topology *userdefinednetworkv1.NetworkTopology `json:"topology,omitempty"`
	// Layer3 is the Layer3 topology configuration.
	Layer3 *Layer3ConfigApplyConfiguration `json:"layer3,omitempty"`
	// Layer2 is the Layer2 topology configuration.
	Layer2 *Layer2ConfigApplyConfiguration `json:"layer2,omitempty"`
	// Localnet is the Localnet topology configuration.
	Localnet *LocalnetConfigApplyConfiguration `json:"localnet,omitempty"`
	// Transport describes the transport technology for pod-to-pod traffic.
	// Allowed values are "NoOverlay" and "EVPN".
	// - "NoOverlay": The network operates in no-overlay mode.
	// - "EVPN": The network uses EVPN transport.
	// When omitted, the network uses the default OVN overlay transport (e.g. Geneve, VXLAN)
	// as configured by ovn-encap-type.
	Transport *userdefinednetworkv1.TransportOption `json:"transport,omitempty"`
	// NoOverlay contains configuration for no-overlay mode.
	// This is only allowed when Transport is "NoOverlay".
	NoOverlay *NoOverlayConfigApplyConfiguration `json:"noOverlay,omitempty"`
	// EVPN contains configuration for EVPN mode.
	// This is only allowed when Transport is "EVPN".
	EVPN *EVPNConfigApplyConfiguration `json:"evpn,omitempty"`
}

// NetworkSpecApplyConfiguration constructs a declarative configuration of the NetworkSpec type for use with
// apply.
func NetworkSpec() *NetworkSpecApplyConfiguration {
	return &NetworkSpecApplyConfiguration{}
}

// WithTopology sets the Topology field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Topology field is set to the value of the last call.
func (b *NetworkSpecApplyConfiguration) WithTopology(value userdefinednetworkv1.NetworkTopology) *NetworkSpecApplyConfiguration {
	b.Topology = &value
	return b
}

// WithLayer3 sets the Layer3 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Layer3 field is set to the value of the last call.
func (b *NetworkSpecApplyConfiguration) WithLayer3(value *Layer3ConfigApplyConfiguration) *NetworkSpecApplyConfiguration {
	b.Layer3 = value
	return b
}

// WithLayer2 sets the Layer2 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Layer2 field is set to the value of the last call.
func (b *NetworkSpecApplyConfiguration) WithLayer2(value *Layer2ConfigApplyConfiguration) *NetworkSpecApplyConfiguration {
	b.Layer2 = value
	return b
}

// WithLocalnet sets the Localnet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Localnet field is set to the value of the last call.
func (b *NetworkSpecApplyConfiguration) WithLocalnet(value *LocalnetConfigApplyConfiguration) *NetworkSpecApplyConfiguration {
	b.Localnet = value
	return b
}

// WithTransport sets the Transport field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Transport field is set to the value of the last call.
func (b *NetworkSpecApplyConfiguration) WithTransport(value userdefinednetworkv1.TransportOption) *NetworkSpecApplyConfiguration {
	b.Transport = &value
	return b
}

// WithNoOverlay sets the NoOverlay field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NoOverlay field is set to the value of the last call.
func (b *NetworkSpecApplyConfiguration) WithNoOverlay(value *NoOverlayConfigApplyConfiguration) *NetworkSpecApplyConfiguration {
	b.NoOverlay = value
	return b
}

// WithEVPN sets the EVPN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EVPN field is set to the value of the last call.
func (b *NetworkSpecApplyConfiguration) WithEVPN(value *EVPNConfigApplyConfiguration) *NetworkSpecApplyConfiguration {
	b.EVPN = value
	return b
}
