// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	userdefinednetworkv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/userdefinednetwork/v1"
)

// NoOverlayConfigApplyConfiguration represents a declarative configuration of the NoOverlayConfig type for use
// with apply.
//
// NoOverlayConfig contains configuration options for networks operating in no-overlay mode.
type NoOverlayConfigApplyConfiguration struct {
	// OutboundSNAT defines the SNAT behavior for outbound traffic from pods.
	OutboundSNAT *userdefinednetworkv1.SNATOption `json:"outboundSNAT,omitempty"`
	// Routing specifies whether the pod network routing is managed by OVN-Kubernetes or users.
	Routing *userdefinednetworkv1.RoutingOption `json:"routing,omitempty"`
}

// NoOverlayConfigApplyConfiguration constructs a declarative configuration of the NoOverlayConfig type for use with
// apply.
func NoOverlayConfig() *NoOverlayConfigApplyConfiguration {
	return &NoOverlayConfigApplyConfiguration{}
}

// WithOutboundSNAT sets the OutboundSNAT field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OutboundSNAT field is set to the value of the last call.
func (b *NoOverlayConfigApplyConfiguration) WithOutboundSNAT(value userdefinednetworkv1.SNATOption) *NoOverlayConfigApplyConfiguration {
	b.OutboundSNAT = &value
	return b
}

// WithRouting sets the Routing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Routing field is set to the value of the last call.
func (b *NoOverlayConfigApplyConfiguration) WithRouting(value userdefinednetworkv1.RoutingOption) *NoOverlayConfigApplyConfiguration {
	b.Routing = &value
	return b
}
