/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	userdefinednetworkv1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/userdefinednetwork/v1"
)

// NoOverlayConfigApplyConfiguration represents a declarative configuration of the NoOverlayConfig type for use
// with apply.
type NoOverlayConfigApplyConfiguration struct {
	OutboundSNAT *userdefinednetworkv1.SNATOption    `json:"outboundSNAT,omitempty"`
	Routing      *userdefinednetworkv1.RoutingOption `json:"routing,omitempty"`
}

// NoOverlayConfigApplyConfiguration constructs a declarative configuration of the NoOverlayConfig type for use with
// apply.
func NoOverlayConfig() *NoOverlayConfigApplyConfiguration {
	return &NoOverlayConfigApplyConfiguration{}
}

// WithOutboundSNAT sets the OutboundSNAT field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OutboundSNAT field is set to the value of the last call.
func (b *NoOverlayConfigApplyConfiguration) WithOutboundSNAT(value userdefinednetworkv1.SNATOption) *NoOverlayConfigApplyConfiguration {
	b.OutboundSNAT = &value
	return b
}

// WithRouting sets the Routing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Routing field is set to the value of the last call.
func (b *NoOverlayConfigApplyConfiguration) WithRouting(value userdefinednetworkv1.RoutingOption) *NoOverlayConfigApplyConfiguration {
	b.Routing = &value
	return b
}
