// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// UserDefinedNetworkStatusApplyConfiguration represents a declarative configuration of the UserDefinedNetworkStatus type for use
// with apply.
//
// UserDefinedNetworkStatus contains the observed status of the UserDefinedNetwork.
type UserDefinedNetworkStatusApplyConfiguration struct {
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// VRFName is the name of the Linux VRF device that OVN-Kubernetes creates
	// for this network on every node where the network is present. It is
	// populated for primary networks. Consumers that must name the VRF, such
	// as FRRConfiguration authors filling in the routers 'vrf' field, should
	// read this value instead of deriving it.
	VRFName *string `json:"vrfName,omitempty"`
}

// UserDefinedNetworkStatusApplyConfiguration constructs a declarative configuration of the UserDefinedNetworkStatus type for use with
// apply.
func UserDefinedNetworkStatus() *UserDefinedNetworkStatusApplyConfiguration {
	return &UserDefinedNetworkStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *UserDefinedNetworkStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *UserDefinedNetworkStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithVRFName sets the VRFName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VRFName field is set to the value of the last call.
func (b *UserDefinedNetworkStatusApplyConfiguration) WithVRFName(value string) *UserDefinedNetworkStatusApplyConfiguration {
	b.VRFName = &value
	return b
}
