//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by openapi-gen. DO NOT EDIT.

package v1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressIP) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.egressip.v1.EgressIP"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressIPList) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.egressip.v1.EgressIPList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressIPSpec) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.egressip.v1.EgressIPSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressIPStatus) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.egressip.v1.EgressIPStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressIPStatusItem) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.egressip.v1.EgressIPStatusItem"
}
