// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PortApplyConfiguration represents a declarative configuration of the Port type for use
// with apply.
//
// Port specifies destination protocol and port on which NetworkQoS
// rule is applied
type PortApplyConfiguration struct {
	// protocol (tcp, udp, sctp) that the traffic must match.
	Protocol *string `json:"protocol,omitempty"`
	// port that the traffic must match
	Port *int32 `json:"port,omitempty"`
}

// PortApplyConfiguration constructs a declarative configuration of the Port type for use with
// apply.
func Port() *PortApplyConfiguration {
	return &PortApplyConfiguration{}
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *PortApplyConfiguration) WithProtocol(value string) *PortApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *PortApplyConfiguration) WithPort(value int32) *PortApplyConfiguration {
	b.Port = &value
	return b
}
