/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	clusternetworkconnectv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/clusternetworkconnect/v1"
	applyconfigurationclusternetworkconnectv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/clusternetworkconnect/v1/apis/applyconfiguration/clusternetworkconnect/v1"
	scheme "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/clusternetworkconnect/v1/apis/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterNetworkConnectsGetter has a method to return a ClusterNetworkConnectInterface.
// A group's client should implement this interface.
type ClusterNetworkConnectsGetter interface {
	ClusterNetworkConnects() ClusterNetworkConnectInterface
}

// ClusterNetworkConnectInterface has methods to work with ClusterNetworkConnect resources.
type ClusterNetworkConnectInterface interface {
	Create(ctx context.Context, clusterNetworkConnect *clusternetworkconnectv1.ClusterNetworkConnect, opts metav1.CreateOptions) (*clusternetworkconnectv1.ClusterNetworkConnect, error)
	Update(ctx context.Context, clusterNetworkConnect *clusternetworkconnectv1.ClusterNetworkConnect, opts metav1.UpdateOptions) (*clusternetworkconnectv1.ClusterNetworkConnect, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterNetworkConnect *clusternetworkconnectv1.ClusterNetworkConnect, opts metav1.UpdateOptions) (*clusternetworkconnectv1.ClusterNetworkConnect, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*clusternetworkconnectv1.ClusterNetworkConnect, error)
	List(ctx context.Context, opts metav1.ListOptions) (*clusternetworkconnectv1.ClusterNetworkConnectList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *clusternetworkconnectv1.ClusterNetworkConnect, err error)
	Apply(ctx context.Context, clusterNetworkConnect *applyconfigurationclusternetworkconnectv1.ClusterNetworkConnectApplyConfiguration, opts metav1.ApplyOptions) (result *clusternetworkconnectv1.ClusterNetworkConnect, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, clusterNetworkConnect *applyconfigurationclusternetworkconnectv1.ClusterNetworkConnectApplyConfiguration, opts metav1.ApplyOptions) (result *clusternetworkconnectv1.ClusterNetworkConnect, err error)
	ClusterNetworkConnectExpansion
}

// clusterNetworkConnects implements ClusterNetworkConnectInterface
type clusterNetworkConnects struct {
	*gentype.ClientWithListAndApply[*clusternetworkconnectv1.ClusterNetworkConnect, *clusternetworkconnectv1.ClusterNetworkConnectList, *applyconfigurationclusternetworkconnectv1.ClusterNetworkConnectApplyConfiguration]
}

// newClusterNetworkConnects returns a ClusterNetworkConnects
func newClusterNetworkConnects(c *K8sV1Client) *clusterNetworkConnects {
	return &clusterNetworkConnects{
		gentype.NewClientWithListAndApply[*clusternetworkconnectv1.ClusterNetworkConnect, *clusternetworkconnectv1.ClusterNetworkConnectList, *applyconfigurationclusternetworkconnectv1.ClusterNetworkConnectApplyConfiguration](
			"clusternetworkconnects",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *clusternetworkconnectv1.ClusterNetworkConnect {
				return &clusternetworkconnectv1.ClusterNetworkConnect{}
			},
			func() *clusternetworkconnectv1.ClusterNetworkConnectList {
				return &clusternetworkconnectv1.ClusterNetworkConnectList{}
			},
		),
	}
}
