// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/networkqos/v1alpha1"
	networkqosv1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/networkqos/v1alpha1/apis/applyconfiguration/networkqos/v1alpha1"
	typednetworkqosv1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/networkqos/v1alpha1/apis/clientset/versioned/typed/networkqos/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeNetworkQoSes implements NetworkQoSInterface
type fakeNetworkQoSes struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.NetworkQoS, *v1alpha1.NetworkQoSList, *networkqosv1alpha1.NetworkQoSApplyConfiguration]
	Fake *FakeK8sV1alpha1
}

func newFakeNetworkQoSes(fake *FakeK8sV1alpha1, namespace string) typednetworkqosv1alpha1.NetworkQoSInterface {
	return &fakeNetworkQoSes{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.NetworkQoS, *v1alpha1.NetworkQoSList, *networkqosv1alpha1.NetworkQoSApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("networkqoses"),
			v1alpha1.SchemeGroupVersion.WithKind("NetworkQoS"),
			func() *v1alpha1.NetworkQoS { return &v1alpha1.NetworkQoS{} },
			func() *v1alpha1.NetworkQoSList { return &v1alpha1.NetworkQoSList{} },
			func(dst, src *v1alpha1.NetworkQoSList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.NetworkQoSList) []*v1alpha1.NetworkQoS { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.NetworkQoSList, items []*v1alpha1.NetworkQoS) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
