//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by openapi-gen. DO NOT EDIT.

package v1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressQoS) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.egressqos.v1.EgressQoS"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressQoSList) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.egressqos.v1.EgressQoSList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressQoSRule) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.egressqos.v1.EgressQoSRule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressQoSSpec) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.egressqos.v1.EgressQoSSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressQoSStatus) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.egressqos.v1.EgressQoSStatus"
}
