// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/uplink/v1alpha1"
	uplinkv1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/uplink/v1alpha1/apis/applyconfiguration/uplink/v1alpha1"
	typeduplinkv1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/uplink/v1alpha1/apis/clientset/versioned/typed/uplink/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeUplinks implements UplinkInterface
type fakeUplinks struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Uplink, *v1alpha1.UplinkList, *uplinkv1alpha1.UplinkApplyConfiguration]
	Fake *FakeK8sV1alpha1
}

func newFakeUplinks(fake *FakeK8sV1alpha1) typeduplinkv1alpha1.UplinkInterface {
	return &fakeUplinks{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Uplink, *v1alpha1.UplinkList, *uplinkv1alpha1.UplinkApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("uplinks"),
			v1alpha1.SchemeGroupVersion.WithKind("Uplink"),
			func() *v1alpha1.Uplink { return &v1alpha1.Uplink{} },
			func() *v1alpha1.UplinkList { return &v1alpha1.UplinkList{} },
			func(dst, src *v1alpha1.UplinkList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.UplinkList) []*v1alpha1.Uplink { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.UplinkList, items []*v1alpha1.Uplink) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
