// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	egressfirewallv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressfirewall/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// EgressFirewallLister helps list EgressFirewalls.
// All objects returned here must be treated as read-only.
type EgressFirewallLister interface {
	// List lists all EgressFirewalls in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*egressfirewallv1.EgressFirewall, err error)
	// EgressFirewalls returns an object that can list and get EgressFirewalls.
	EgressFirewalls(namespace string) EgressFirewallNamespaceLister
	EgressFirewallListerExpansion
}

// egressFirewallLister implements the EgressFirewallLister interface.
type egressFirewallLister struct {
	listers.ResourceIndexer[*egressfirewallv1.EgressFirewall]
}

// NewEgressFirewallLister returns a new EgressFirewallLister.
func NewEgressFirewallLister(indexer cache.Indexer) EgressFirewallLister {
	return &egressFirewallLister{listers.New[*egressfirewallv1.EgressFirewall](indexer, egressfirewallv1.Resource("egressfirewall"))}
}

// EgressFirewalls returns an object that can list and get EgressFirewalls.
func (s *egressFirewallLister) EgressFirewalls(namespace string) EgressFirewallNamespaceLister {
	return egressFirewallNamespaceLister{listers.NewNamespaced[*egressfirewallv1.EgressFirewall](s.ResourceIndexer, namespace)}
}

// EgressFirewallNamespaceLister helps list and get EgressFirewalls.
// All objects returned here must be treated as read-only.
type EgressFirewallNamespaceLister interface {
	// List lists all EgressFirewalls in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*egressfirewallv1.EgressFirewall, err error)
	// Get retrieves the EgressFirewall from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*egressfirewallv1.EgressFirewall, error)
	EgressFirewallNamespaceListerExpansion
}

// egressFirewallNamespaceLister implements the EgressFirewallNamespaceLister
// interface.
type egressFirewallNamespaceLister struct {
	listers.ResourceIndexer[*egressfirewallv1.EgressFirewall]
}
