// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

// EgressFirewallListerExpansion allows custom methods to be added to
// EgressFirewallLister.
type EgressFirewallListerExpansion interface{}

// EgressFirewallNamespaceListerExpansion allows custom methods to be added to
// EgressFirewallNamespaceLister.
type EgressFirewallNamespaceListerExpansion interface{}
