// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

// EgressQoSListerExpansion allows custom methods to be added to
// EgressQoSLister.
type EgressQoSListerExpansion interface{}

// EgressQoSNamespaceListerExpansion allows custom methods to be added to
// EgressQoSNamespaceLister.
type EgressQoSNamespaceListerExpansion interface{}
