// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	cache "k8s.io/client-go/tools/cache"

	vtepv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/vtep/v1/apis/listers/vtep/v1"
)

// VTEPInformer is an autogenerated mock type for the VTEPInformer type
type VTEPInformer struct {
	mock.Mock
}

// Informer provides a mock function with no fields
func (_m *VTEPInformer) Informer() cache.SharedIndexInformer {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Informer")
	}

	var r0 cache.SharedIndexInformer
	if rf, ok := ret.Get(0).(func() cache.SharedIndexInformer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cache.SharedIndexInformer)
		}
	}

	return r0
}

// Lister provides a mock function with no fields
func (_m *VTEPInformer) Lister() vtepv1.VTEPLister {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Lister")
	}

	var r0 vtepv1.VTEPLister
	if rf, ok := ret.Get(0).(func() vtepv1.VTEPLister); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vtepv1.VTEPLister)
		}
	}

	return r0
}

// NewVTEPInformer creates a new instance of VTEPInformer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVTEPInformer(t interface {
	mock.TestingT
	Cleanup(func())
}) *VTEPInformer {
	mock := &VTEPInformer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
