---
global:
  measurements:
    - name: podLatency
    - name: pprof
      pprofInterval: 1m
      pprofDirectory: pprof-data
      pprofTargets:
      - name: ovnkube-controller
        namespace: "ovn-kubernetes"
        labelSelector: {app: ovnkube-node}
        url: http://localhost:9410/debug/pprof/profile?seconds=30
      - name: ovnkube-control-plane
        namespace: "ovn-kubernetes"
        labelSelector: {name: ovnkube-control-plane}
        url: http://localhost:9411/debug/pprof/profile?seconds=30
      - name: ovnkube-controller-heap
        namespace: "ovn-kubernetes"
        labelSelector: {app: ovnkube-node}
        url: http://localhost:9410/debug/pprof/heap?seconds=30
      - name: ovnkube-control-plane-heap
        namespace: "ovn-kubernetes"
        labelSelector: {name: ovnkube-control-plane}
        url: http://localhost:9411/debug/pprof/heap?seconds=30
jobs:
  - name: udn-density-l2-pods-netpol
    jobIterations: 100
    qps: 10
    burst: 10
    namespacedIterations: true 
    namespace: udn-density-l2-pods-netpol
    waitWhenFinished: true
    podWait: false 
    preLoadImages: false 
    preLoadPeriod: 2m
    churnConfig:
      percent: 10
      cycles: 10
      mode: objects
    objects:

      - objectTemplate: workloads/templates/udn-density/udn_l2.yml
        replicas: 1

      - objectTemplate: workloads/templates/udn-density/np-deny-all.yml
        replicas: 1

      - objectTemplate: workloads/templates/udn-density/np-allow-from-clients.yml
        replicas: 1

      - objectTemplate: workloads/templates/udn-density/service.yml
        replicas: 1

      - objectTemplate: workloads/templates/udn-density/deployment-server.yml
        replicas: 1

      - objectTemplate: workloads/templates/udn-density/deployment-client.yml
        replicas: 1
