// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// EgressIPSpecApplyConfiguration represents a declarative configuration of the EgressIPSpec type for use
// with apply.
//
// EgressIPSpec is a desired state description of EgressIP.
type EgressIPSpecApplyConfiguration struct {
	// EgressIPs is the list of egress IP addresses requested. Can be IPv4 and/or IPv6.
	// This field is mandatory.
	EgressIPs []string `json:"egressIPs,omitempty"`
	// NamespaceSelector applies the egress IP only to the namespace(s) whose label
	// matches this definition. This field is mandatory.
	NamespaceSelector *metav1.LabelSelectorApplyConfiguration `json:"namespaceSelector,omitempty"`
	// PodSelector applies the egress IP only to the pods whose label
	// matches this definition. This field is optional, and in case it is not set:
	// results in the egress IP being applied to all pods in the namespace(s)
	// matched by the NamespaceSelector. In case it is set: is intersected with
	// the NamespaceSelector, thus applying the egress IP to the pods
	// (in the namespace(s) already matched by the NamespaceSelector) which
	// match this pod selector.
	PodSelector *metav1.LabelSelectorApplyConfiguration `json:"podSelector,omitempty"`
}

// EgressIPSpecApplyConfiguration constructs a declarative configuration of the EgressIPSpec type for use with
// apply.
func EgressIPSpec() *EgressIPSpecApplyConfiguration {
	return &EgressIPSpecApplyConfiguration{}
}

// WithEgressIPs adds the given value to the EgressIPs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EgressIPs field.
func (b *EgressIPSpecApplyConfiguration) WithEgressIPs(values ...string) *EgressIPSpecApplyConfiguration {
	for i := range values {
		b.EgressIPs = append(b.EgressIPs, values[i])
	}
	return b
}

// WithNamespaceSelector sets the NamespaceSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespaceSelector field is set to the value of the last call.
func (b *EgressIPSpecApplyConfiguration) WithNamespaceSelector(value *metav1.LabelSelectorApplyConfiguration) *EgressIPSpecApplyConfiguration {
	b.NamespaceSelector = value
	return b
}

// WithPodSelector sets the PodSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodSelector field is set to the value of the last call.
func (b *EgressIPSpecApplyConfiguration) WithPodSelector(value *metav1.LabelSelectorApplyConfiguration) *EgressIPSpecApplyConfiguration {
	b.PodSelector = value
	return b
}
