// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// EgressIPStatusItemApplyConfiguration represents a declarative configuration of the EgressIPStatusItem type for use
// with apply.
//
// The per node status, for those egress IPs who have been assigned.
type EgressIPStatusItemApplyConfiguration struct {
	// Assigned node name
	Node *string `json:"node,omitempty"`
	// Assigned egress IP
	EgressIP *string `json:"egressIP,omitempty"`
}

// EgressIPStatusItemApplyConfiguration constructs a declarative configuration of the EgressIPStatusItem type for use with
// apply.
func EgressIPStatusItem() *EgressIPStatusItemApplyConfiguration {
	return &EgressIPStatusItemApplyConfiguration{}
}

// WithNode sets the Node field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Node field is set to the value of the last call.
func (b *EgressIPStatusItemApplyConfiguration) WithNode(value string) *EgressIPStatusItemApplyConfiguration {
	b.Node = &value
	return b
}

// WithEgressIP sets the EgressIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EgressIP field is set to the value of the last call.
func (b *EgressIPStatusItemApplyConfiguration) WithEgressIP(value string) *EgressIPStatusItemApplyConfiguration {
	b.EgressIP = &value
	return b
}
