// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressfirewall/v1"
	egressfirewallv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressfirewall/v1/apis/applyconfiguration/egressfirewall/v1"
	typedegressfirewallv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressfirewall/v1/apis/clientset/versioned/typed/egressfirewall/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeEgressFirewalls implements EgressFirewallInterface
type fakeEgressFirewalls struct {
	*gentype.FakeClientWithListAndApply[*v1.EgressFirewall, *v1.EgressFirewallList, *egressfirewallv1.EgressFirewallApplyConfiguration]
	Fake *FakeK8sV1
}

func newFakeEgressFirewalls(fake *FakeK8sV1, namespace string) typedegressfirewallv1.EgressFirewallInterface {
	return &fakeEgressFirewalls{
		gentype.NewFakeClientWithListAndApply[*v1.EgressFirewall, *v1.EgressFirewallList, *egressfirewallv1.EgressFirewallApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("egressfirewalls"),
			v1.SchemeGroupVersion.WithKind("EgressFirewall"),
			func() *v1.EgressFirewall { return &v1.EgressFirewall{} },
			func() *v1.EgressFirewallList { return &v1.EgressFirewallList{} },
			func(dst, src *v1.EgressFirewallList) { dst.ListMeta = src.ListMeta },
			func(list *v1.EgressFirewallList) []*v1.EgressFirewall { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.EgressFirewallList, items []*v1.EgressFirewall) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
