name: cleanup
on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  cleanup:
    if: github.repository == 'ovn-org/ovn-kubernetes'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cleanup
        uses: ./.github/actions/cleanup-action
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow_id: 926245
