name: 'Close stale Issues and Warn stale PRs'
on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          # Issue related configurations go here
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
          exempt-all-issue-milestones: true
          exempt-issue-labels: 'kind/ci-flake'
          stale-issue-label: 'lifecycle/stale'
          days-before-issue-stale: 60
          days-before-issue-close: 5
          # PR related configurations go here
          stale-pr-message: 'This PR is stale because it has been open 90 days with no activity. Remove stale label or comment or reach out to maintainers for code reviews or consider closing this if you do not plan to work on it.'
          exempt-all-pr-milestones: true
          stale-pr-label: 'lifecycle/stale'
          days-before-pr-stale: 90
          # we never close a PR
          days-before-pr-close: -1
