#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
# SPDX-License-Identifier: Apache-2.0

"""
Post performance reports as comments to GitHub PRs.

Supports:
- Multiple PRs
- Multiple workload reports
- Automatic chunking for large comments (GitHub 65k limit)
- Collapsible sections per workload

Usage:
    python post-pr-comment.py --pr 123 --reports-dir ./reports --run-id 456 --status success
"""

import argparse
import os
import sys
from pathlib import Path

import requests


MAX_COMMENT_SIZE = 60000  # GitHub limit is 65536


def get_github_token() -> str:
    """Get GitHub token from environment."""
    token = os.getenv('GITHUB_TOKEN')
    if not token:
        print("Error: GITHUB_TOKEN environment variable not set", file=sys.stderr)
        sys.exit(1)
    return token


def get_repo_info() -> tuple[str, str]:
    """Get repository owner and name from environment."""
    repo = os.getenv('GITHUB_REPOSITORY')
    if repo and '/' in repo:
        owner, name = repo.split('/', 1)
        return owner, name

    print("Error: GITHUB_REPOSITORY environment variable not set", file=sys.stderr)
    sys.exit(1)


def find_reports(reports_dir: Path) -> list[dict[str, str]]:
    """
    Find all performance report markdown files in the reports directory.

    Returns:
        List of dicts with 'workload' and 'content' keys
    """
    reports = []

    if not reports_dir.exists():
        return reports

    for workload_dir in reports_dir.iterdir():
        if not workload_dir.is_dir():
            continue

        # Look for performance_report.md in the workload directory
        report_file = workload_dir / 'performance_report.md'

        if report_file.exists():
            content = report_file.read_text()
            reports.append({
                'workload': workload_dir.name,
                'content': content
            })
            print(f"Found report for workload: {workload_dir.name}", file=sys.stderr)

    return reports


def build_header(run_id: str, run_url: str, status: str, baseline_id: str = None,
                baseline_url: str = None, part_num: int = None, total_parts: int = None) -> str:
    """Build the comment header."""
    header = "## 🚀 Performance Test Results"

    if part_num is not None and total_parts is not None:
        header += f" (Part {part_num}/{total_parts})"

    header += "\n\n"
    header += f"**Status:** {'✅ Completed' if status == 'success' else '❌ Failed'}\n"
    header += f"**Workflow Run:** [#{run_id}]({run_url})\n"

    if baseline_id and baseline_url:
        header += f"**Baseline:** [Daily run #{baseline_id}]({baseline_url})\n"

    header += "\n---\n\n"

    return header


def create_comment_chunks(reports: list[dict], run_id: str, run_url: str, status: str,
                         baseline_id: str = None, baseline_url: str = None) -> list[str]:
    """
    Create comment chunks, splitting if necessary to fit GitHub's size limit.

    Returns:
        List of comment bodies ready to post
    """
    footer = "\n---\n🤖 Generated by performance-report workflow"

    if not reports:
        # Generate a basic report if no detailed reports exist
        basic_report = build_header(run_id, run_url, status, baseline_id, baseline_url)

        if status == 'success':
            basic_report += "### Results Summary\n"
            basic_report += "Performance test completed successfully.\n\n"
            basic_report += "**Artifacts Available:**\n"
            basic_report += "- Performance metrics data\n"
            basic_report += "- Cluster logs\n"
        else:
            basic_report += "### ⚠️ Test Failed\n"
            basic_report += f"The performance test failed to complete. Please check the [workflow logs]({run_url}) for details.\n"

        basic_report += footer
        return [basic_report]

    # Build individual workload sections as collapsible details
    workload_sections = []
    for report in reports:
        section = f"<details>\n<summary><strong>{report['workload']}</strong></summary>\n\n"
        section += report['content']
        section += "\n</details>\n\n"
        workload_sections.append(section)

    # Try to fit all in one comment first
    single_comment = build_header(run_id, run_url, status, baseline_id, baseline_url)
    single_comment += f"**Workloads Tested:** {len(reports)}\n\n---\n\n"
    single_comment += ''.join(workload_sections)
    single_comment += footer

    if len(single_comment) <= MAX_COMMENT_SIZE:
        return [single_comment]

    # Need to chunk - split workloads across multiple comments
    print(f"Comment too large ({len(single_comment)} chars), chunking...", file=sys.stderr)

    chunks = []
    current_chunk = ''
    current_workloads = []

    for i, section in enumerate(workload_sections):
        test_chunk = current_chunk + section

        # Estimate with header and footer (conservative)
        estimated_size = len(test_chunk) + 500

        if estimated_size > MAX_COMMENT_SIZE and current_chunk:
            # Current chunk is full, save it and start new one
            chunks.append({
                'content': current_chunk,
                'workloads': current_workloads.copy()
            })
            current_chunk = section
            current_workloads = [reports[i]['workload']]
        else:
            current_chunk = test_chunk
            current_workloads.append(reports[i]['workload'])

    # Add the last chunk
    if current_chunk:
        chunks.append({
            'content': current_chunk,
            'workloads': current_workloads
        })

    # Build final comments with part numbers
    total_parts = len(chunks)
    comments = []

    for idx, chunk in enumerate(chunks):
        part_num = idx + 1
        comment = build_header(run_id, run_url, status, baseline_id, baseline_url, part_num, total_parts)
        comment += f"**Workloads in this part:** {', '.join(chunk['workloads'])}\n\n"
        comment += "---\n\n"
        comment += chunk['content']
        comment += footer
        comments.append(comment)

    return comments


def post_comment(owner: str, repo: str, pr_number: int, body: str, token: str) -> bool:
    """Post a comment to a PR."""
    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments"
    headers = {
        'Authorization': f'token {token}',
        'Accept': 'application/vnd.github.v3+json'
    }

    data = {'body': body}

    response = requests.post(url, headers=headers, json=data)

    if response.status_code == 201:
        return True
    else:
        print(f"Failed to post comment: {response.status_code} {response.text}", file=sys.stderr)
        return False


def main():
    parser = argparse.ArgumentParser(description='Post performance reports to GitHub PRs')
    parser.add_argument('--pr', type=int, action='append', dest='prs',
                        help='PR number(s) to comment on (can specify multiple)')
    parser.add_argument('--reports-dir', type=Path, required=True,
                        help='Directory containing workload report subdirectories')
    parser.add_argument('--run-id', required=True, help='Workflow run ID')
    parser.add_argument('--run-url', required=True, help='Workflow run URL')
    parser.add_argument('--status', required=True, choices=['success', 'failure'],
                        help='Workflow conclusion status')
    parser.add_argument('--baseline-id', help='Baseline run ID')
    parser.add_argument('--baseline-url', help='Baseline run URL')
    parser.add_argument('--owner', help='Repository owner (default: from GITHUB_REPOSITORY)')
    parser.add_argument('--repo', help='Repository name (default: from GITHUB_REPOSITORY)')

    args = parser.parse_args()

    if not args.prs:
        print("No PRs specified, nothing to do", file=sys.stderr)
        return 0

    # Get repo info
    if args.owner and args.repo:
        owner, repo = args.owner, args.repo
    else:
        owner, repo = get_repo_info()

    token = get_github_token()

    # Find all reports
    reports = find_reports(args.reports_dir)

    # Create comment chunks
    comment_chunks = create_comment_chunks(
        reports,
        args.run_id,
        args.run_url,
        args.status,
        args.baseline_id,
        args.baseline_url
    )

    print(f"Generated {len(comment_chunks)} comment chunk(s)", file=sys.stderr)

    # Post all chunks to each PR
    success_count = 0
    total_posts = len(args.prs) * len(comment_chunks)

    for pr_number in args.prs:
        for i, chunk in enumerate(comment_chunks):
            print(f"Posting part {i + 1}/{len(comment_chunks)} to PR #{pr_number}...", file=sys.stderr)

            if post_comment(owner, repo, pr_number, chunk, token):
                success_count += 1
                print(f"  ✓ Posted successfully", file=sys.stderr)
            else:
                print(f"  ✗ Failed to post", file=sys.stderr)

    print(f"\nPosted {success_count}/{total_posts} comment(s) successfully", file=sys.stderr)

    return 0 if success_count == total_posts else 1


if __name__ == '__main__':
    sys.exit(main())
