// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressservice/v1"
	egressservicev1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressservice/v1/apis/applyconfiguration/egressservice/v1"
	typedegressservicev1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressservice/v1/apis/clientset/versioned/typed/egressservice/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeEgressServices implements EgressServiceInterface
type fakeEgressServices struct {
	*gentype.FakeClientWithListAndApply[*v1.EgressService, *v1.EgressServiceList, *egressservicev1.EgressServiceApplyConfiguration]
	Fake *FakeK8sV1
}

func newFakeEgressServices(fake *FakeK8sV1, namespace string) typedegressservicev1.EgressServiceInterface {
	return &fakeEgressServices{
		gentype.NewFakeClientWithListAndApply[*v1.EgressService, *v1.EgressServiceList, *egressservicev1.EgressServiceApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("egressservices"),
			v1.SchemeGroupVersion.WithKind("EgressService"),
			func() *v1.EgressService { return &v1.EgressService{} },
			func() *v1.EgressServiceList { return &v1.EgressServiceList{} },
			func(dst, src *v1.EgressServiceList) { dst.ListMeta = src.ListMeta },
			func(list *v1.EgressServiceList) []*v1.EgressService { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.EgressServiceList, items []*v1.EgressService) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
