// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

// EgressServiceListerExpansion allows custom methods to be added to
// EgressServiceLister.
type EgressServiceListerExpansion interface{}

// EgressServiceNamespaceListerExpansion allows custom methods to be added to
// EgressServiceNamespaceLister.
type EgressServiceNamespaceListerExpansion interface{}
