package test

// This list contains separate lists of informing and blocking tests. Tests not
// on either of these lists do not run. To graduate a test from informing to
// blocking:
//  1. Remove the tests from InformingTests list and add it to the BlockingTests list
//  2. Rebuild: ./hack/build-tests-ext.sh
//  3. Verify: ./bin/ovn-kubernetes-tests-ext list tests | jq -r '.[] | select(.name == "test name here") | .lifecycle'
//
// Used by: openshift/cmd/ovn-kubernetes-tests-ext/main.go

// InformingTests lists tests that generally pass but are not considered stable
// and should not block CI jobs if they fail.
var InformingTests = []string{
	// EVPN tests
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF When a pod runs on the tested network Can reach KAPI service [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF When a pod runs on the tested network It can be reached by an external server on the same network When the network is IPv4 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF When a pod runs on the tested network It can be reached by an external server on the same network When the network is IPv6 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF When a pod runs on the tested network It cannot be reached by a cluster node When it is a different node When the network is IPv4 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF When a pod runs on the tested network It cannot be reached by a cluster node When it is a different node When the network is IPv6 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF When a pod runs on the tested network It cannot be reached by an external server on a different network When the network is IPv4 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF When a pod runs on the tested network It cannot be reached by an external server on a different network When the network is IPv6 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF When a pod runs on the tested network It can reach external servers on the same network When the network is IPv4 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF When a pod runs on the tested network It can reach external servers on the same network When the network is IPv6 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF When a pod runs on the tested network When other pod runs on the tested network On a different node Backing a ClusterIP service The first pod can reach the ClusterIP service on the same network When the networks are IPv4 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF When a pod runs on the tested network When other pod runs on the tested network On a different node Backing a ClusterIP service The first pod can reach the ClusterIP service on the same network When the networks are IPv6 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF When a pod runs on the tested network When other pod runs on the tested network On a different node The pods on the tested network can reach each other When the networks are IPv4 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF When a pod runs on the tested network When other pod runs on the tested network On a different node The pods on the tested network can reach each other When the networks are IPv6 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF When a pod runs on the tested network When there is other network Of type Default Both networks are isolated [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF When a pod runs on the tested network When there is other network Of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF Both networks are isolated [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF When a pod runs on the tested network When there is other network Of type Layer 2 CUDN EVPN MAC-VRF Both networks are isolated [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF When a pod runs on the tested network When there is other network Of type Layer 2 UDN Both networks are isolated [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF When a pod runs on the tested network When there is other network Of type Layer 3 CUDN EVPN IP-VRF Both networks are isolated [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF When a pod runs on the tested network When there is other network Of type Layer 3 UDN Both networks are isolated [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 3 CUDN EVPN IP-VRF When a pod runs on the tested network Can reach KAPI service [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 3 CUDN EVPN IP-VRF When a pod runs on the tested network It can be reached by an external server on the same network When the network is IPv4 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 3 CUDN EVPN IP-VRF When a pod runs on the tested network It can be reached by an external server on the same network When the network is IPv6 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 3 CUDN EVPN IP-VRF When a pod runs on the tested network It cannot be reached by a cluster node When it is a different node When the network is IPv4 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 3 CUDN EVPN IP-VRF When a pod runs on the tested network It cannot be reached by a cluster node When it is a different node When the network is IPv6 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 3 CUDN EVPN IP-VRF When a pod runs on the tested network It cannot be reached by an external server on a different network When the network is IPv4 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 3 CUDN EVPN IP-VRF When a pod runs on the tested network It cannot be reached by an external server on a different network When the network is IPv6 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 3 CUDN EVPN IP-VRF When a pod runs on the tested network It can reach external servers on the same network When the network is IPv4 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 3 CUDN EVPN IP-VRF When a pod runs on the tested network It can reach external servers on the same network When the network is IPv6 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 3 CUDN EVPN IP-VRF When a pod runs on the tested network When other pod runs on the tested network On a different node Backing a ClusterIP service The first pod can reach the ClusterIP service on the same network When the networks are IPv4 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 3 CUDN EVPN IP-VRF When a pod runs on the tested network When other pod runs on the tested network On a different node Backing a ClusterIP service The first pod can reach the ClusterIP service on the same network When the networks are IPv6 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 3 CUDN EVPN IP-VRF When a pod runs on the tested network When other pod runs on the tested network On a different node The pods on the tested network can reach each other When the networks are IPv4 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 3 CUDN EVPN IP-VRF When a pod runs on the tested network When other pod runs on the tested network On a different node The pods on the tested network can reach each other When the networks are IPv6 [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 3 CUDN EVPN IP-VRF When a pod runs on the tested network When there is other network Of type Default Both networks are isolated [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 3 CUDN EVPN IP-VRF When a pod runs on the tested network When there is other network Of type Layer 2 CUDN EVPN MAC-VRF and IP-VRF Both networks are isolated [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 3 CUDN EVPN IP-VRF When a pod runs on the tested network When there is other network Of type Layer 2 CUDN EVPN MAC-VRF Both networks are isolated [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 3 CUDN EVPN IP-VRF When a pod runs on the tested network When there is other network Of type Layer 2 UDN Both networks are isolated [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 3 CUDN EVPN IP-VRF When a pod runs on the tested network When there is other network Of type Layer 3 CUDN EVPN IP-VRF Both networks are isolated [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] BGP: For BGP configured networks When the tested network is of type Layer 3 CUDN EVPN IP-VRF When a pod runs on the tested network When there is other network Of type Layer 3 UDN Both networks are isolated [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] EVPN: VTEP API validations api-server should accept valid VTEP CRs Valid VTEP configurations [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] EVPN: VTEP API validations api-server should accept valid VTEP updates Valid VTEP update configurations [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] EVPN: VTEP API validations api-server should reject invalid VTEP CRs Invalid VTEP configurations [Suite:openshift/conformance/parallel]",
	"[Feature:EVPN][Feature:RouteAdvertisements][ovn-kubernetes-ote][sig-network] EVPN: VTEP API validations api-server should reject invalid VTEP updates Invalid VTEP update configurations [Suite:openshift/conformance/parallel]",
}

// BlockingTests lists tests that are considered stable and should block CI jobs
// if they fail.
var BlockingTests = []string{}
